### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by lludol** [vime-js/vime#100]
Hello,

I can't make working the Audio player on iPhone.
I have two problems:
1) the audio is not played after clicking on the Play icon AND the timer display "aN:aN" instead of the duration
2) the icons of the player are not displayed

**For the 1):**
Here is a screen of the bug on iPhone 11 Pro iOS 13:
![iphone-11-pro-bug](https://user-images.githubusercontent.com/5556262/97079988-ddaf5b00-1600-11eb-931a-d0b35047b045.PNG)
So you can see that there is the icons but the duration is wrong. Also here is the error when I click on the play button:
```
[Vime warn]: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

**For the 2):**
Here is a screen on iPhone 7 iOS 12:
![iphone-7-ios12-bug](https://user-images.githubusercontent.com/5556262/97080022-14857100-1601-11eb-8a95-8f16ca0b1df3.PNG)
As you can see there is no icons and of course the audio is not working.

Here is the code of the player:
```javascript
import {
	VimePlayer, VimeUi, VimeAudio, VimeIcon, VimeControl, VimeCurrentTime, VimeEndTime, VimeScrubberControl, VimeIcons, VimeControls, VimePlaybackControl,
} from '@vime/react';
import {
	FunctionComponent, useRef, useState,
} from 'react';
import styled from 'styled-components';

import PlayerStore from '../data/PlayerStore';

const StyledPlayer = styled.div`
	position: fixed;
	bottom: 0px;
	width: 100%;
	z-index: 10;
	background: white;

	& > :first-child {
		@media (min-width: 768px) {
			width: 50%;
			margin-right: auto;
			margin-left: auto;
		}
	}
`;

const StyledProgressTime = styled(VimeControls)`
	margin: 0px;
	--vm-slider-value-color: ${(props) => props.theme.red};
	--vm-controls-padding: 0px;
`;
const StyledTimeControl = styled(VimeControls)`
	justify-content: space-between !important;
	height: 22px;
	margin: 0px;
	padding: 0px 15px;

	--vm-time-font-size: 14px;
	--vm-time-color: #000;
	font-family: Lato;
	`;

const StyledCurrentTime = styled(VimeCurrentTime)`
	--vm-time-color: ${(props) => props.theme.red};
`;

const StyledButtonsControl = styled(VimeControls)`
	margin: 0px;
	justify-content: unset !important;
	--vm-controls-padding: 0px 0px 0px 20px;
	flex-wrap: nowrap;
`;

const StyledAudioTitleContainer = styled.div`
	display: flex;
	flex-grow: 2;
`;

const StyledightButtonContainer = styled.div`
	display: flex;
	flex-grow: 1;
`;

const StyledPlayButton = styled(VimePlaybackControl)`
	margin-right: 10px;
`;

const StyledAudioTitle = styled.p`
	padding-left: 10px;
	font-size: 14px;

	@media (max-width: 768px) {
		font-size: 3.5vw;
	}
`;

export const Player: FunctionComponent = () => {
	const currentAudio = PlayerStore.useState((s) => s.currentAudio);
	const currentKey = PlayerStore.useState((s) => s.key);

	const player = useRef<HTMLVimePlayerElement>(null);
	const [currentTime, setCurrentTime] = useState(0);

	const refresh = () => {
		setCurrentTime(0);
	};

	const onTimeUpdate = (event: CustomEvent<number>) => {
		setCurrentTime(event.detail);
	};

	if (!currentAudio) {
		return null;
	}

	return (
		<StyledPlayer>
			<VimePlayer ref={player} key={currentKey} autoplay={false} debug={true} theme="light" currentTime={currentTime} onVCurrentTimeChange={onTimeUpdate}>
				<VimeAudio mediaTitle={currentAudio.title}>
					<source data-src={currentAudio.url} type="audio/mp3" />
				</VimeAudio>

				<VimeUi>
					<StyledProgressTime fullWidth>
						<VimeScrubberControl />
					</StyledProgressTime>
					<StyledTimeControl fullWidth>
						<StyledCurrentTime />
						<VimeEndTime />
					</StyledTimeControl>
					<VimeIcons href="/play.svg" />
					<StyledButtonsControl fullWidth>
						<StyledightButtonContainer>
							<VimeControl label={'Refresh'} onClick={refresh}>
								<VimeIcon href="#vime-refresh" />
							</VimeControl>
						</StyledightButtonContainer>
						<StyledAudioTitleContainer>
							<StyledAudioTitle>{currentAudio.title}</StyledAudioTitle>
						</StyledAudioTitleContainer>
						<StyledightButtonContainer>
							<StyledPlayButton />
							 <VimeControl label={'Forward'}>
								<VimeIcon href="#vime-seek-forward" />
							</VimeControl>
						</StyledightButtonContainer>
					</StyledButtonsControl>
				</VimeUi>
			</VimePlayer>
		</StyledPlayer>
	);
};
```

As you can see I disabled the autoplay, online people are saying that it's not working on iOS so I disabled it for the test.

Everything is working well on my laptop with Google Chrome for example and on my Android phone. It's only on iOS that I have problems. (I tried also with Google Chrome on the iPhone but it's not working, same problem).

**How did you manage to make the player works on iOS ?**

Thank you.

**Comment by mihar-22** [comment]
Hey @lludol I'll need to look into this because I think there is an issue when attempting to play on iOS with a custom control, it's not being recognized as the user initiating playback (programmatic initiation instead) which it is rejecting. I see it happening on the Vime audio demo on iOS as well.

I'm not sure what's happening with icons and the duration not showing. I'll see if I can get a BrowserStack account so I can test these out.

**Comment by excid3** [comment]
I think I'm having th esame issue on Safari 14 on macOS. 

Clicking Play switches the icon then immediately goes back. If I seek, I get the same error:

```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
2attemptToPlay — 77.3d2b735b.js:286
```

Gif of the issue:
![safari](https://p198.p4.n0.cdn.getcloudapp.com/items/WnurnLZ9/Screen%20Recording%202020-11-06%20at%2008.37.45%20PM.gif)

**Comment by wplit** [comment]
Confirmed on Safari 14 on macOS also.

**Comment by excid3** [comment]
Thanks @mihar-22!

Is vimejs.com using the new release? I'm still having the same issue on vimejs.com and cloning and running the HTML example. Maybe the CDN hasn't been updated for 4.4.0 yet?

**Comment by mihar-22** [comment]
Hey @excid3 no problem! I haven't updated the docs site (vimejs.com) just yet (doing it now), also the CDN doesn't update straight away. In the HTML example if you explicitly set the version `http://cdn.jsdelivr.net/npm/@vime/core@4.4.0/dist/vime/vime.esm.js` then it'll load the in the latest, otherwise CDN takes time to update.

**Comment by excid3** [comment]
Works perfect in Safari 14 on macOS, thanks @mihar-22! You're a champ. 💪

**Comment by wplit** [comment]
For me it's not working, see https://codepen.io/wplit/pen/mdEaPBL

For clarity, I see it working on the vime demo site, but I can't recreate the demo. Safari macbook and mobile, the audio never loads, the active class is never added.

**Comment by timothysu** [comment]
> I think I'm having th esame issue on Safari 14 on macOS.
> 
> Clicking Play switches the icon then immediately goes back. If I seek, I get the same error:
> 
> ```
> Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
> 2attemptToPlay — 77.3d2b735b.js:286
> ```
> 
> Gif of the issue: https://a.cl.ly/WnurnLZ9

this issue (the play button and seeking not working) still occurs if there's any attempt to `autoplay`, but it works just fine in safari if not. any thoughts?
