### ISSUE TITLE
Cannot get HLS video to play in Angular app

### ISSUE THREAD

**Issue by leighhopcroft** [vime-js/vime#104]
I'm struggling to sucessfully get HLS video to play using @vime/angular. See https://codesandbox.io/s/amazing-euclid-j2lpz?file=/src/app/app.component.html

Could someone advise where I might be going wrong?

**Comment by mihar-22** [comment]
Hey @leighhopcroft  should be fixed in `4.3.3`, sandbox works after upgrading :) Something strange going on in Angular where it's disconnecting the element and reconnecting it for no reason. I'll need to look into this later.
