### ISSUE TITLE
The angular version does not support Angular Ivy

### ISSUE THREAD

**Issue by ergo04** [vime-js/vime#105]
This is the error: "This likely means that the library (@vime/angular/dist) which declares VimeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy".

**Comment by mihar-22** [comment]
I'm not exactly sure what I would need to do to make the library Angular Ivy compatible, because the [docs suggest](https://angular.io/guide/creating-libraries#publishing-your-library) to not publish Ivy libraries, and I'm simply using `ng-packagr` to do the work with no real special settings.

**Comment by mihar-22** [comment]
This should be resolved in Vime 5 now, upgrade to the latest package and please let me know if it's not 👍

**Comment by ergo04** [comment]
It works now. Thank you very much 🙏🏻
