### ISSUE TITLE
Audioplayer not loading in Safari

### ISSUE THREAD

**Issue by wplit** [vime-js/vime#106]
Both macbook and iOS safari

See https://codepen.io/wplit/pen/mdEaPBL

It's a replicated of the vime demo page (where it does work), but when using the CDN it doesn't.

**Comment by mihar-22** [comment]
I can't reproduce locally, does this happen locally or only in the sandbox environment?

**Comment by wplit** [comment]
I'm only ever using vime direct from the CDN, but on a local site I get the same, no console errors, just the player is never active, and if I remove the skeleton manually, and then add the active class, so I can see the player, clicking play still won't actually play the audio..

https://www.loom.com/share/017a8ef9811249d19b8ea869d275dd02

**Comment by wplit** [comment]
Solved, it wasn't a bug in the player, it was something i was doing incorrectly.
