### ISSUE TITLE
Problem with hls provider + react

### ISSUE THREAD

**Issue by ViacheslavBurlaka** [vime-js/vime#107]
I saw some important issue when worked with hls and this pretty player.

steps to reproduce at [https://vimejs.com/demo](https://vimejs.com/demo) or in you own project
1. react 
2. chose **hls** provider
3. insert **track** tag with subtitles
then the player started to bug and playback stopped. You can check this on demo page and i have the same behavior in my project

code looks like this:

`
  <VimePlayer
    theme="dark"
    style={{ '--vm-player-theme': '#e86c8b' }}
  >
    <VimeHls
      crossOrigin
      poster="https://media.vimejs.com/poster.png"
    >
      <source 
        data-src="https://media.vimejs.com/hls/index.m3u8" 
        type="application/x-mpegURL" 
      />
      <track 
        default 
        kind="subtitles" 
        src="https://media.vimejs.com/subs/english.vtt" 
        srclang="en" 
        label="English" 
      />
    </VimeHls>
    <VimeDefaultUi />
  </VimePlayer>
`
<img width="675" alt="hls+react+issue" src="https://user-images.githubusercontent.com/16492645/99132324-75abcd80-261e-11eb-9911-f00fb8359abd.png">

Please let's find out what the problem

**Comment by mihar-22** [comment]
Hey @ViacheslavBurlaka that's a mistake on my end, I'll be fixing the docs to mention you don't load tracks via the `<track>` element, they need to be specified in the HLS manifest (`.m3u8` file).

**Comment by ViacheslavBurlaka** [comment]
Hi @mihar-22 ! Thx for quick response. Please tell me,
I have .m3u8 file without embedded subtitles and separated .srt subtitles in another file. Is it mean that I have no choice to insert some subtitles to player?

**Comment by mihar-22** [comment]
Your use-case is a little special since you are dynamically retrieving them, unfortunately for now I don't have a solution for you. However, this plugin (https://github.com/vime-js/vime/issues/12) which I'll be working on very soon will allow you to load subtitles from anywhere, and do more advanced stuff which will solve your problem.

**Comment by mihar-22** [comment]
If you have any feature suggestions that'll help you, feel free to open a new issue :)

**Comment by ViacheslavBurlaka** [comment]
Thx a lot but it sounds a little bit sadly) i have no option to convert format from .srt to another. That's mean I need to looking for another video player?) or maybe in near feature you can find solution for this use case? I think that's not rare and very popular situation. At many streaming platforms developers have only srt subtitles sources and src link for .m3u8. And i cannot find solution anywhere, it's disappointing..

**Comment by mihar-22** [comment]
Okay @ViacheslavBurlaka for the captions I'll look at adding a SRT to WebVTT converter so it can accept SRT files.

**Comment by blmhemu** [comment]
@ViacheslavBurlaka FFmpeg can convert srt to webvtt (If you are willing to follow that route for the moment)
