### ISSUE TITLE
Issue with nextjs

### ISSUE THREAD

**Issue by nkrmr** [vime-js/vime#109]
When I tried to use vimejs with nextjs, I have these two issues :

<img width="957" alt="Screenshot 2020-11-15 at 12 16 58" src="https://user-images.githubusercontent.com/686395/99183496-86526580-273c-11eb-80ec-1b2dde6a23a3.png">

<img width="956" alt="Screenshot 2020-11-15 at 12 17 10" src="https://user-images.githubusercontent.com/686395/99183500-8a7e8300-273c-11eb-95a9-1abc8d52314c.png">

**it's seems that it doesn't pass the videoId on video-embed**

<img width="842" alt="Screenshot 2020-11-15 at 12 51 05" src="https://user-images.githubusercontent.com/686395/99184149-55c0fa80-2741-11eb-8dc6-b747742e95f3.png">

Do you have an idea of what's appends?

Best regards

**Comment by mihar-22** [comment]
Was this resolved with the latest version of TypeScript?

**Comment by nkrmr** [comment]
> Was this resolved with the latest version of TypeScript?

No, it's a bug with Nextjs. I don't know if I made good integration. Do you have any examples with NextJS ?

**Comment by mihar-22** [comment]
Working on few things, when I have some time I'll prepare a nextjs example and debug it.

**Comment by nodgear** [comment]
> Working on few things, when I have some time I'll prepare a nextjs example and debug it.

Hey, i'm having some other problems as well with NextJS, have you got any spare time recently to do q quick check on it?

**Comment by aldrakos** [comment]
Hi all,
I am also having some issues with Next.js, in my case the requires on the /cjs/components/index.js do not work
eg `var Audio_1 = __importDefault(require("./Audio"));` does not work with `Error: Cannot find module './Audio'` but changing to
`var Audio_1 = __importDefault(require("./Audio.jsx"));`  imports that module (and then errors on that file's `../lib` import)

Any ideas here?

**Comment by aldrakos** [comment]
Update:
Seems next.js does not compile dependencies.
The solution, ss metioned on this stackoverflow answer:
https://stackoverflow.com/a/67486361
is to use the `next-transpile-modules` package and use it to transpile the vime libs in next.config.js:
```
const withTM = require('next-transpile-modules')(['@vime/core', '@vime/react']);

module.exports = withTM({
  <normal next.js config here>
});
```
This does increase the build/load times in dev, but it does solves the problems for me!

**Comment by nodgear** [comment]
> Update:
> Seems next.js does not compile dependencies.
> The solution, as metioned on this stackoverflow answer (https://stackoverflow.com/a/67486361) is to use the `next-transpile-modules` package and use it to transpile the vime libs in `next.config.js`:
> 
> ```
> const withTM = require('next-transpile-modules')(['@vime/core', '@vime/react']);
> 
> module.exports = withTM({
>   <normal next.js config here>
> });
> ```
> 
> This does increase the build/load times in dev, but it does solves the problems for me!

What about using the dynamic module from next and settings SSR to false? have you tried if that helps?
Video players are client-side anyway, so having it load on client is not a bad design.

**Comment by aldrakos** [comment]
> > Update:
> > Seems next.js does not compile dependencies.
> > The solution, as metioned on this stackoverflow answer (https://stackoverflow.com/a/67486361) is to use the `next-transpile-modules` package and use it to transpile the vime libs in `next.config.js`:
> > ```
> > const withTM = require('next-transpile-modules')(['@vime/core', '@vime/react']);
> > 
> > module.exports = withTM({
> >   <normal next.js config here>
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This does increase the build/load times in dev, but it does solves the problems for me!
> 
> What about using the dynamic module from next and settings SSR to false? have you tried if that helps?
> Video players are client-side anyway, so having it load on client is not a bad design.

I will look into this thanks! Although I am doing SSG and I am pretty sure next.js hydrates all needed files client-side (e.g. the vime/react  js files are module imported on the page's js file). So this loads on the client side regardless (plus it's the react components that we are using). Also it would still have the problem of bringing in those modules without transpiling them (since I think the vime/react assumes the files will be part of a build process with eg babel/webpack)

**Comment by Alissonsleal** [comment]
Had this same problem, @nodgear's solution work really well.

Here's how I did it:
- Created a Player component
```js
import { Player as VimePlayer, Hls, DefaultUi } from '@vime/react'

const Player = () => (
  <VimePlayer theme="dark">
    <Hls crossOrigin poster="https://media.vimejs.com/poster.png">
      <source
        data-src="https://media.vimejs.com/hls/index.m3u8"
        type="application/x-mpegURL"
      />
    </Hls>

    <DefaultUi />
  </VimePlayer>
)

export default Player
```

- And then I imported with `next/dynamic`

```js
const Player = dynamic(() => import('~/components/Player'), {
  ssr: false,
})


const Page = () => {
  <div>
    <Player />
  </div>
}

export default Page
```

**Comment by icephonix1111** [comment]
Thanks 😊

**Comment by nodgear** [comment]
This issue should be closed now, the solution is importing with dynamic import.
This is actually standard for most players with exception to videojs

**Comment by dankerizer** [comment]
thank you @Alissonsleal

**Comment by jsonpreet** [comment]
> 

Hey, I am using same way, But getting ./Audio error
