### ISSUE TITLE
HTML5 player controls do not disappear completely.

### ISSUE THREAD

**Issue by blmhemu** [vime-js/vime#112]
![image](https://user-images.githubusercontent.com/19410501/99215553-4604ed00-27f9-11eb-8802-4fb76d063c0f.png)

Here is the code : https://pastebin.com/k3bf8FJN

Framework : Sapper

Sorry for spamming with bugs :)

**Comment by mihar-22** [comment]
Ah the `controls` property should not be set on `vime-player` if you're using the custom Vime controls. That's why you have 2 controls. The `controls` property is to show the native controls for the provider.

**Comment by blmhemu** [comment]
@mihar-22 Just realized that. Sorry for the silly question.
