### ISSUE TITLE
Vime tries to load maxresdefault.jpg for undefined video

### ISSUE THREAD

**Issue by gabrielnemeth** [vime-js/vime#125]
When using the youtube provider, the Vime player tries to retrieve `maxresdefault.jpg` to `undefined` video, which of course gives 404.

![image](https://user-images.githubusercontent.com/11211316/101536571-7aa03a80-399a-11eb-8ee1-870a26f94005.png)

Steps to reproduce:
- open https://vimejs.com/demo/
- open network tab in the developer toolbar
- switch to youtube provider
- check the console and network tab

**Comment by mihar-22** [comment]
Should be resolved now in this [commit](https://github.com/vime-js/vime/commit/5acb6c7c38382010a67efc3c6f3c47010e2f6d87).
