### ISSUE TITLE
Upcoming 5.0.0 Release - What's Coming?!

### ISSUE THREAD

**Issue by mihar-22** [vime-js/vime#126]
# Introduction

Hey guys, if you think I've been MIA then guess again! Actually I have been. Slightly busy with life things but I've also been working on the library in the dark, and 🥁 ... there's a lot coming in the next release! Probably some of the most requested features I've seen across most open-source players, and a few BIG announcements. I'll give some sneak peaks but just know they're all still in talks and not finalized:

- 🏛️  &nbsp;I can't say who yet because it hasn't been finalized... but Vime is being tested and implemented in a top 10 U.S website. I'll let you use your imagination, I'm sure you've all used it.
- 🤝  &nbsp;There'll potentially be a joining of forces.
- 💼  &nbsp;Still early but few new friends and I have been talking and testing if we can create something to make the video space a lot easier for us all. I'm really excited about this one. I'll share more when I can.

# What's in the next release?

The next release is mostly focusing on consistency and bringing the library to a place I think we all would expect it to be (this means a lot of internal rewrites and new features). It's about rectifying a lot of the mistakes in `v4` which are painfully obvious. From an API standpoint there aren't a crazy amount of changes that can't be easily fixed without a simple `find and replace`, I'll be listing [migration](#migration) notes below.

**IMPORTANT:** None of the changes below have been finalized just yet, so feel free to chime in and let me know what your thoughts are in the comments below. I'll be updating this over time.

## Juicy Features

- **Shadow DOM baby!** I made a stupid mistake of not using it from the start because I thought it would help you guys be more free querying and manipulating the DOM. Turns out it breaks the library due to styles not being encapsulated (who would of thought?). Not only that but if you tried to set `class` or `style` attribute on a Vime component it was messing up as it was overlapping with the internal styles because I set them on the `<Host>` element. It was probably also ugly that all the styles `<style>` were being jammed into your `<head>`. You are all now safe my children. The Shadow DOM will protect us and keep all your styles and the Vime styles separate. We've been saved!
- **New icon library system.** It was probably really awkward trying to go and create your own SVG sprite and try to replacing the icons in the player. I know because I tried and it sucked. Well I did some digging and I found this really sweet library called [Shoelace](http://shoelace.style/), which is a beautifully simple UI web component library. I stole their approach and I'm not ashamed. I'm actually pretty good at copy pasting. Anyway... so now we have icon libraries and Vime comes out of the box with the default Vime icon set and the new Material icon set. I'll add more in the future. It's super easy to add your own, to switch between sets, and you can even select a library or icon on a control by control use-case. There'll be more information about it in the docs.
- **Provider switching.** You can change providers dynamically now, so one moment you can be using HLS and in the next whatever you like. Sweeeeeeeeeet.
- **HLS/DASH audio tracks and video quality support.** This is probably the one I think most people really need. There is an API for getting/setting the audio tracks and video qualities when using the HLS/DASH providers. In addition, the audio tracks and playback qualities are automatically synced with custom settings menu 🤩 
- **New captions interface.** Rewrote this stuff from the ground up because it was just a mess and I couldn't support additional providers such as HLS and DASH. So it basically means that, you have new properties and events on the player for captions management AND now Vime supports captions with HLS and Dash. The custom Vime captions and settings UI now supports it too.
- **Dynamic mobile UI.** Originally the UI would determine if it was a mobile device based on the UA string and it would just stay that way. It wasn't really reliable and only accounted for certain mobile phones. Now we use a `ResizeObserve` and dynamically adapt for mobile devices when the screen size is below `480px`. It will also jump back to desktop mode when you go back above `480px`. Nice right?
- **New loading screen.** I felt like the skeleton loading screen was ugly. I got rid of it and I'll be replacing it with a custom and simple loading screen. I also want you to be able to replace it with your own logo/branding so that'll be nice. 
- ~~**Moving to LitElement.** So Stencil has been pretty cool but overall I'm not too crazy about slow transpilation times that are ruining my developer experience. I also feel the library is quite bloated because the internals for Stencil alone without any polyfills is `120KB`! It's time to move towards something more lightweight and make the library more enjoyable to use and work with. This should mean performance goes up, bundle size goes down, and developers go from depressed to happy.~~ Moving this down the pipeline.
- **Cleaner touch styling.** This is a small change but styling for touch devices uses rounded highlights to match your thumb instead of a square. There's also pressed feedback now, which is when your holding your thumb on an element such as a control.
- **Smoother settings UI.** The settings has been revamped with some new animations. It just feels a little nicer to use and less jumpy. I know some people appreciate the small things.
- **Naming is more consistent across the library.** The CSS variables were already using the prefix `vm` but the components were using `vime` such as `vime-video`, and events were using `v` such as `vPlay`. This is obviously silly so everything is `vm` now. Examples: `vm-video`, `--vm-player-font-family`, `vmPlay`.
- **Less pollution.** I think it was probably annoying when working with a framework integration (React/Vue...) that everything had 4 useless characters in front of it such as `VimePlayer`, `VimeVideo` and so on. Everything is simple now, no Vime prefix anymore so the examples again would be `Player` and `Video` such as `import { Player } from '@vime/react';`.
- **Attributes over classes for styling.** Most components including the player were styled based on classes before such as `vime-player.mobile`, due to using the Shadow DOM and steering away from placing styles on the host element, everything is attributes now such as `vime-player[mobile]` or `vime-player[mobile="true"]`.
- ~~**New site/docs.** I haven't started work on this and I'm not 100% sure if this will coincide with `v5` release, but I want to renew the entire site and documentation. Feels ugly. Time for new stuff. **Recommend me something!**~~ Moving this down the pipeline.

## Internals

- No more SaSS. Only CSS.
- `findRootPlayer` has been renamed to `findPlayer` and is asynchronous now as it retries firing events to find the player.
- `usePlayerContext` is also `async` now thanks to `findPlayer`.
- New controls collision detection system/registry. Also replaced `controlsHeight` prop on components that were repositioning based on controls to a CSS variable called `--vm-controls-height`. Simply register for controls collision detection now and use the CSS variable as needed.
- Removed all E2E tests as they were way too flaky and no matter what I couldn't get them to behave consistently. It would be hit or miss every time. I was anxious on every `git push`, no more!
- Refactored all the player and `MediaProvider` internals and moved logic into mixins such as `withPlayerScheduler`.
- Created a component registry that dynamically tracks component registrations, and allows components to watch for changes and find other components. It can be useful in specific situations.

## Migrating

There are not too many scary API changes, as mentioned earlier most can be fixed by a simple `find and replace`.

- All component, event and CSS variables are prefixed now with `vm`. Components have gone from `vime-video` to `vm- video`, events from `vPlay` to `vmPlay`, and CSS variables remain the same as before `--vm-player-font-family`.
- Component names have been simplified for framework integrations by removing the prefix `Vime`. So it looks like this now when using React/Vue/Angular/Svelte -> `import { Player, Video, DefaultUi } from '@vime/x';`. Before it was `import { VimePlayer, VimeVideo, VimeDefaultUi } from '@vime/x';`.
- Skeleton has been removed from the default UI and with it the `noSkeleton` property. You can add this back manually yourself if you want it.
- The `attached` property and `vmAttached` event has been removed from the player component.
- The `vime-icons` component has been removed and replaced by `vm-icon-library`.
- The icons folder in the root `@vime/core` package has been moved. Icons are now kept in sets under the `icons` folder, so `icons/vime` and `icons/material`.
- Auto-generated `ids` now use the `vm` prefix instead of `vime`.
- The icon component accepts a `src` prop instead of a `href` prop.
- No `errors` property exists on the player, all errors are emitted from the `vmError` event instead of `vErrorsChange`.
- Removed the ability to provide static files such as `.mp4` to `vm-file` with a `quality` property that would dynamically update based on device width. This is something better suited to dynamic streams such as HLS/DASH, and it's not a supported feature by browsers anymore.
- Removed `loadSprite` helper from all exports.

**Comment by wplit** [comment]
Nice one!

**Comment by ViacheslavBurlaka** [comment]
Sounds exciting! I look forward to the release

**Comment by PhilippMDoerner** [comment]
Looking forward to checking this one out!

**Comment by mihar-22** [comment]
Vime 5 is now out 🥳 

See the [Release Notes](https://vimejs.com/welcome/release-notes#migrating-v4-to-v5) for the latest. 

Go ahead and start playing!
