### ISSUE TITLE
Video player height issues

### ISSUE THREAD

**Issue by gabrielnemeth** [vime-js/vime#132]
I don't know if I'm implementing something wrong, or it's a bug, but the video player height is 40px by default. I've tested Youtube, Vimeo, Dailymotion so far. On the demo page, the video won't load, but the player itself is also 40px [(https://vimejs.com/demo/)](https://vimejs.com/demo/).

![video (Small)](https://user-images.githubusercontent.com/11211316/102645786-4e877500-4163-11eb-8022-a5bcfc485fcf.PNG)

I've tried also in plain Angular 11 project with the same result. I can't provide a stackblitz example, because as soon as I import the `VimeModule` I'm getting a `Failed to execute 'define' on 'CustomElementRegistry': parameter 2 is not of type 'Function'.`

The tested vime version is the latest 5.0.8.

**Comment by mihar-22** [comment]
Hey @gabrielnemeth I just released version 5 of the library and there's something funky going on with YouTube/Vimeo/Dailymotion providers. I'll fix this after the weekend on Monday.
