### ISSUE TITLE
Embeds are automatically playing on the demo page without autoplay set to true

### ISSUE THREAD

**Issue by mihar-22** [vime-js/vime#143]
The embeds (YouTube/Vimeo/Dailymotion) seem to autoplay even when it is set to `false` on the [demo](https://vimejs.com/demo) page. This might be related to the React integration and the fact that some properties are set late, since the React integration can't update properties until one tick later.

**Comment by Amerlander** [comment]
I have the same issue using svelte/sapper. Local MP4 is not autoplaying, but YouTube does:

```svelte
<script>
    import { Player, Youtube, DefaultUi } from '@vime/svelte';
    export let data;
</script>

{#if (process.browser) }
    <Player
    theme="dark"
    style="--vm-player-theme: #e86c8b;"
    autoplay="false"
    >
    <Youtube videoId="{data}" />
    
    <DefaultUi />
    </Player>
{/if}
```

**Comment by magicspon** [comment]
I'm also seeing this when using with React.

**Comment by silllli** [comment]
I am also having this issue with Svelte / Sapper.

**Comment by logan-jobzmall** [comment]
Same here with Angular
