### ISSUE TITLE
Fullscreen not working properly

### ISSUE THREAD

**Issue by Draco241** [vime-js/vime#147]
Issue: When i entering fullscreen for the first time it's working properly, but if i want to exit from fullscreen i got 
"Uncaught (in promise) Error: Fullscreen API is not available."

Versions:
Vime: 5.0.19

Provider: HLS

**Comment by mihar-22** [comment]
What browser/version and how did it happen? Did you click the fullscreen control or call `player.enterFullscreen()`?

**Comment by Draco241** [comment]
@mihar-22 I tried on 2 browsers Firefox 84.0, Chromium 83.0.4103.116. It's happening when i click on the fullscreen control or when i using my keyboard to toggle fullscreen.

**Comment by ViacheslavBurlaka** [comment]
bug is relevant - can only open fullscreen, but cannot close by click on button (exit fullscreen) or by dbclick on view

hls+react+chrome+macos

**Comment by ViacheslavBurlaka** [comment]
and sometimes have this error `Uncaught TypeError: _this$fullscreen2.destroy is not a function`

**Comment by ViacheslavBurlaka** [comment]
and additionally, `isFullscreenActive`  from `usePlayerContext` doesn't toggle too

**Comment by dolbex** [comment]
> bug is relevant - can only open fullscreen, but cannot close by click on button (exit fullscreen) or by dbclick on view
> 
> hls+react+chrome+macos

This also happens Chrome + MacOS, Firefox + MacOS. I can sometimes close, when I reopen fullscreen the context menu for download then appears (It's not there the first time)

**Comment by dolbex** [comment]
Apologies - kiddo learning piano in the background :) 

https://user-images.githubusercontent.com/954095/110822650-44a37880-825f-11eb-94d2-a8f36ba783d0.mov

**Comment by koaie** [comment]
any follow up?

**Comment by marcelfahle** [comment]
Yup, same for me. Try this:
Start the player on [vimejs.com](https://vimejs.com/), click fullscreen, exit fullscreen again, and then click any other page in the sidebar. The error shows up in the console

**Comment by rossng** [comment]
The fullscreen button stops working for me after the first click. Here's a sample of the errors I see in the console:

```
Uncaught (in promise) Error: Fullscreen API is not available.
    React 11
        enterFullscreen
        asyncGeneratorStep
        _next
        promise callback*asyncGeneratorStep
        _next
        promise callback*asyncGeneratorStep
        _next
        _asyncToGenerator
        _asyncToGenerator
        enterFullscreen
        onClick
```

**Comment by rossng** [comment]
It seems that the problem comes from the fact that Vime is only attempting to use the Webkit-specific method to enter/exit fullscreen here: https://github.com/vime-js/vime/blob/b09eb82c3e3375edf5e1552287aa141e422cced8/src/components/providers/file/file.tsx#L449

I can see elsewhere in the codebase that there is an abstracted API for cross-browser fullscreen, but the `File` component doesn't use it for some reason. I don't really understand Vime's DI system well enough to contribute a fix yet.

**Comment by mihar-22** [comment]
This should be fixed in the latest release `5.0.30` 🎉  Apologies on the delay, hard to find time lately. Test it out and let me know how it goes!

**Comment by rossng** [comment]
Brilliant - this does indeed seem to fix it for me. I really appreciate your hard work on this library ☺

**Comment by Enigma10** [comment]
@mihar-22 fullscreen API is not working IOS safari and safari web browser Version 14.0.3 (16610.4.3.1.7).
