### ISSUE TITLE
docs: broken links to light and dark themes

### ISSUE THREAD

**Issue by benbro** [vime-js/vime#154]
# Documentation

**Documentation page URL:**
https://vimejs.com/

**Reason:**
The links to the light and dark themes in this sentence are broken.
```Style anything you want with CSS variables. Default light and dark themes are included.```
https://github.com/vime-js/vime/blob/master/packages/core/src/globals/themes/light.css
https://github.com/vime-js/vime/blob/master/packages/core/src/globals/themes/default.css

**Comment by dgabriel123** [comment]
@benbro is it cool if I work on this issue?

**Comment by mihar-22** [comment]
Go for it @dgabriel123 that's be awesome!

**Comment by mihar-22** [comment]
If you have any issues jump in our [Discord](https://discord.com/invite/feZ6cAE) and I can help you.

**Comment by mihar-22** [comment]
Closed in #155.
