### ISSUE TITLE
bug: can not find player nextjs when directly loading the page which is having the player

### ISSUE THREAD

**Issue by Enigma10** [vime-js/vime#158]
**Vime version:**
5.0.19
**Provider:**
HLS

I am working on nextjs application and I am trying to access the page which is having the player. I am getting these errors. But If I am going through a different page then it is working fine. Any help is big help 

[
![Screenshot from 2021-01-08 17-30-37](https://user-images.githubusercontent.com/14229196/104014873-c3d1ed00-51d9-11eb-8ac2-f260c1698e73.png)
![Screenshot from 2021-01-08 17-30-27](https://user-images.githubusercontent.com/14229196/104014878-c59bb080-51d9-11eb-9831-6559795502cc.png)

](URL)

This is my code. 

```import {
  Player as VimePlayer,
  Hls,
  DefaultUi,
  DefaultControls,
  Controls,
} from "@vime/react";
import "twin.macro";

import "@vime/core/themes/default.css";

import { StreamInterface } from "../../types/types";
export const Player = ({ stream }: { stream: StreamInterface }) => {
  const hlsConfig = {};

  return (
    <VimePlayer autoplay aspectRatio="16:9">
      <Hls
        version="latest"
        config={hlsConfig}
        poster={stream.thumbnail_url_small}
        mediaTitle={stream.title}
      >
        <source data-src={stream.conf.hls} type="application/x-mpegURL" />
      </Hls>

      <DefaultUi noControls noCaptions>
        <Controls hideOnMouseLeave={false} pin="topRight">
          share
        </Controls>
        <DefaultControls hideOnMouseLeave activeDuration={2000} />
      </DefaultUi>
    </VimePlayer>
  );
};
```

**Comment by Enigma10** [comment]
hi, @mihar-22 sorry to tag you directly but this is an issue causing issue problem for us. can you help me with this?

**Comment by hkngoc** [comment]
Have you fixed the error yet?

I have the same error too :((

**Comment by hkngoc** [comment]
I was fixed that error by change video player component to client side render.
