### ISSUE TITLE
bug: 'vm-player' is not a known element:

### ISSUE THREAD

**Issue by ChrisK1994** [vime-js/vime#167]
# Bug Report

**Vime version:**
 "@vime/angular": "^5.0.27",

**Current behavior:**
Element not recognized

**Expected behavior:**
Element recognized

I copied the example from [vime-github ](https://github.com/vime-js/vime/tree/master/examples/angular) and it shows me this message, why?

**Comment by Wernerson** [comment]
I'm having the same issue.

I did `npm i --save @vime/angular` and imported `VimeModule` but it's showing the same error message.

@ChrisK1994 how did you solve this?

Vime version 5.0.33

**Comment by ChrisK1994** [comment]
sorry, i don't remember
