### ISSUE TITLE
Default UI changes to browser default UI in full-screen

### ISSUE THREAD

**Issue by dalalRohit** [vime-js/vime#173]
When toggling between FullScreen, player UI changes from `<DefaultUi />` to browser native `<video>` UI

## Default UI is visible 
![half](https://user-images.githubusercontent.com/32014253/111118673-1ab7c200-858f-11eb-817c-f122fe8beaaa.PNG)

## Default UI is replaced by `<video>` controls UI
![full](https://user-images.githubusercontent.com/32014253/111118682-1d1a1c00-858f-11eb-85ae-e3dd3a62aacb.PNG)

Also, can escape full-screen via ESC only, clicking on the FullScreen icon is throwing the error:

`
 [Deprecation] 'HTMLVideoElement.webkitEnterFullscreen()' is deprecated. Please use 'Element.requestFullscreen()' instead.
`

**Comment by smilga** [comment]
I encountered with same error. Is there any known workaround?
P.S Thanks @mihar-22 for amazing project. It's really pleasure to work with it :)

**Comment by mihar-22** [comment]
Duplicate of #147.
