### ISSUE TITLE
bug: vime.js video is not working IE , getting Syntax error in main.daea68bd.js. Can you please help me with this

### ISSUE THREAD

**Issue by 321vka** [vime-js/vime#205]
<
![image](https://user-images.githubusercontent.com/83404176/120629217-368e7e00-c483-11eb-9cb3-da67cfb296a1.png)

**Comment by surajjha-dev** [comment]
Yeah, It's not working in IE browser I'm facing the same issue.

**Comment by mihar-22** [comment]
Hey @321vka and @surajjha-dev! IE is a deprecated browser that's reached end of life (no more support from Microsoft). As stated in the `README.md` this library is future focused (modern browsers) and doesn't support it either way. Apologies for any inconvenience.
