### ISSUE TITLE
bug/documentation: Webpack/Angular compatibility 

### ISSUE THREAD

**Issue by jbjhjm** [vime-js/vime#209]
Hi, currently, v 5.0.31 , the custom-elements source file is transpiled to es2019.
This will fail to work with Webpack < v5, as it does not support es2019 (see https://github.com/webpack/webpack/issues/10227).
Which means that atm, vime is only compatible with webpack 5 and angular 12 (due to angular < 12 using webpack 4).

This should either be noted in documentation, because many many applications are not using the latest webpack/angular versions...

Or, even better, it could be fixed by providing the custom-elements source at a lower es standard.
(Which I'd obviously prefer, currently I'm using npm postinstall script to overwrite it with a custom-transpiled es6 version to make it work. Ugly.)

**Comment by jbjhjm** [comment]
Looking into package.json, the babel transpilation added in https://github.com/vime-js/vime/commit/1445dc42a33ef7929aaa137edd818dcb5aa38da6  is not included anymore.

However tsconfig-build.json still specifies target = esnext which will not transpile es2019/es2020 features. 
Correcting this to es6 should fix the issue.

**Comment by mihar-22** [comment]
Should be resolved now in `5.0.32`.
