### ISSUE TITLE
Event Listeners

### ISSUE THREAD

**Issue by mehulmpt** [vime-js/vime#21]
Sorry if it is buried somewhere in the documentation, but I did not find any way to attach event listeners to the player state like `onend`  (I'm embedded YouTube videos). I tried using the `player.$on('data')` event listener as described in the docs, but for YouTube embeds, it never fires the callback - I'm not using any `sendCommand`

Let me know what is the current state for that. Thanks!

**Comment by mehulmpt** [comment]
Oops, got it. The player uses state subscription, missed it. Sorry for bugging!

**Comment by mihar-22** [comment]
Ye I was worried that might confuse some people. If you have any suggestion where I could put a callout or something to avoid this issue then please let me know :)

**Comment by mehulmpt** [comment]
Nah I think it's fine right now. Just need to dig in a bit in the docs, a few examples on the top would be great involving some handling of events showing the use of the store.
