### ISSUE TITLE
bug: Nuxt.js support version 5.0.31

### ISSUE THREAD

**Issue by 1shaked** [vime-js/vime#218]
I am using Vime and with version 5.0.28 and that works fine when I upgrade to version 5.0.31 I get an error. When running local and with docker.

RROR in ./node_modules/@vime/core/dist/custom-elements/index.js 20:15
#9 16.44 Module parse failed: Unexpected token (20:15)
#9 16.44 You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
#9 16.44 |     timeout = setTimeout(() => {
#9 16.44 |       if (attempt === maxRetries) {
#9 16.44 >         onFail?.();
#9 16.44 |         return;
#9 16.44 |       }
#9 16.44  @ ./node_modules/@vime/vue/dist/esm/index.js 1:0-84 1:0-84 1:0-84 1:0-84 1:0-84
#9 16.44  @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/test.vue?vue&type=script&lang=js&
#9 16.44  @ ./components/test.vue?vue&type=script&lang=js&
#9 16.44  @ ./components/test.vue
#9 16.44  @ ./.nuxt/components/plugin.js
#9 16.44  @ ./.nuxt/index.js
#9 16.44  @ ./.nuxt/client.js
#9 16.44  @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
#9 16.44 
#9 16.44  FATAL  Nuxt build error
#9 16.44 
#9 16.44   at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
#9 16.44   at processTicksAndRejections (internal/process/task_queues.js:95:5)
#9 16.44   at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
#9 16.44   at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
#9 16.44   at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
#9 16.44   at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
#9 16.44 
#9 16.44 
#9 16.44    ╭─────────────────────────────╮
#9 16.44    │                             │
#9 16.44    │   ✖ Nuxt Fatal Error        │
#9 16.44    │                             │
#9 16.44    │   Error: Nuxt build error   │

# Bug Report

**Vime version:**

**Current behavior:**
failed to build when running docker image

**Steps to reproduce:**
create nuxt app add vime via install 

and create a component with client only tag as a wrapper

`<template>
  <div>
    <div>
      <Player controls style="display: none">
        <Youtube video-id="cFUPSjWfKcU" />
      </Player>
      <Player controls>
        <video-player crossorigin="" poster="https://media.vimejs.com/poster.png">
          
          
          <source data-src="https://media.vimejs.com/720p.mp4" type="video/mp4">
          <track
            default
            kind="subtitles"
            src="https://media.vimejs.com/subs/english.vtt"
            srclang="en"
            label="English"
          >
        </video-player>
      </Player>
    </div>
  </div>
</template>

<script>
// import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import { Player, Youtube, Video } from '@vime/vue'

export default {
  components: {
    Player,
    'video-player': Video,
    Youtube
  },
  data () {
    return {
      svg: 'flashes',
      // editor: ClassicEditor,
      editorData: '<p>Content of the editor.</p>',
      editorConfig: {
        // The configuration of the editor.
      }
    }
  },
  methods: {
    changeSVG () {
      this.svg = 'main'
    }
  }
}
</script>
<style scoped>
div {
  background-color: black;
  border: 1px solid red;
}
</style>
`
run docker build with version 5.0.31 and with version 5.0.28

**Related code:**
![Screen Shot 2021-07-01 at 12 13 17](https://user-images.githubusercontent.com/40497915/124098980-bc432080-da65-11eb-8690-a0ff54066621.png)

**Other information:**

**Comment by sniperadmin** [comment]
@1shaked 
in nuxt config, just add the package in the transpile array like this

```js
build: {
  transpile: ["@vime/vue", "@vime/core"]
}
```

**Comment by 1shaked** [comment]
I will try thanks will update soon

**Comment by sniperadmin** [comment]
Absolutely! pleasure to help!

**Comment by 1shaked** [comment]
Works thanks
