### ISSUE TITLE
bug: React integration broken

### ISSUE THREAD

**Issue by AntonOfTheWoods** [vime-js/vime#236]
# Bug Report
The following commit appears to have broken at least the react example (`TapSidesToSeek`):

https://github.com/vime-js/vime/commit/df41fd36f524864a7a82324c314f59f879a81885

From that point, all calls to `usePlayerContext` appear to fail, and simply return the default provided value.

**Vime version:**
From 5.0.15+ (including `main`)

**Provider:**
All

**Current behavior:**
all calls to `usePlayerContext` appear to fail, and simply return the default provided value.

**Expected behavior:**
all calls to `usePlayerContext` should not fail, and should not simply return the default provided value.

**Steps to reproduce:**

Check out a fresh copy of main and follow the instructions to test the React example. Clicking on the sides does not advance/return the currentTime by 5 seconds.

**Related code:**

packages/react/src/lib.tsx

**Comment by AntonOfTheWoods** [comment]
Actually it looks like just the lines:
```
const [isVideoView] = usePlayerContext(ref, 'isVideoView', false);
const [isPlaybackReady] = usePlayerContext(ref, 'playbackReady', false);
```
(https://github.com/vime-js/vime/blob/main/examples/react/src/TapSidesToSeek.tsx#L17)
Always return false. If those are removed then the example does work as expected. No idea what state I got in so that `duration` was also giving me -1.

**Comment by czaplej** [comment]
There is problem witch cache. IF u disable network cache in browser it's works fine, also if u define 
`<source data-src={"`${url}?cb=${new Date().getTime()}`"} />` It's works

**Comment by AntonOfTheWoods** [comment]
Thanks

**Comment by austinfox** [comment]
This bug still exists, and I'm not sure its actually because of the cache. Taking a look at [the official react documentation on useRef](https://reactjs.org/docs/hooks-reference.html), it says 

> Keep in mind that useRef doesn’t notify you when its content changes. Mutating the .current property doesn’t cause a re-render. If you want to run some code when React attaches or detaches a ref to a DOM node, you may want to use a callback ref instead.

And in all the examples for custom components, usePlayerContext is taking in a ref. But this ref is initialized as null, and then the value is updated but doesn't trigger a re-render. usePlayerContext was actually passed null (I have confirmed this myself) and never gets the real ref value. In this case, it defaults to the default value passed in as the 3rd argument.

**Comment by austinfox** [comment]
This doesn't appear to be fixed, can we re-open it? Is there a better fix we can use? I can't disable network caching for client browsers and the mentioned fix with the added "cb=${new Date().getTime()}" query parameter is not working for me. I'm able to get things to work if I trigger a re-render of the component via updating state via hooks, but this is not ideal by any means.
