### ISSUE TITLE
Vime not works in Angular 11.2.4

### ISSUE THREAD

**Issue by airtonlima** [vime-js/vime#261]
I installed the library as per the documentation, but it's not working in my project. The error occurs when I run ng serve.

Installed version:

    "@vime/angular": "^5.0.34",
    "@vime/core": "^5.0.34",

Error Message:

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 941:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1093:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1233:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1294:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1418:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1443:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1497:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 1702:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2075:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2370:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2639:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2722:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2805:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 2967:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 3109:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 3223:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4130:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4470:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4557:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4591:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4614:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4686:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 4970:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5066:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5091:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5129:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5207:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5267:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 5519:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6103:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6190:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6248:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6408:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6533:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6604:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6644:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6745:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6825:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6906:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6930:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 6955:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 7008:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 7144:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 7540:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

Error: ./node_modules/@vime/core/dist/custom-elements/index.js 7704:4-16
"export 'attachShadow' was not found in '@stencil/core/internal/client'

**Comment by GNURub** [comment]
Same with Angular 12

**Comment by jaybi4** [comment]
We just found out that the latest version of [stencil](https://www.npmjs.com/package/@stencil/core) 2.10.0 is the cause. With version 2.8.0 it didn't happen.

**Comment by airtonlima** [comment]
Thank you for the information!!
It worked here with the following versions:

"@stencil/core": "2.8.0",
"@vime/angular": "5.0.33",
"@vime/core": "5.0.33",

**Comment by mihar-22** [comment]
Thanks for catching this @jaybi4! I've downgraded `@stecil/core` and releasing fix now.
