### ISSUE TITLE
bug: vm-player is not a known element:

### ISSUE THREAD

**Issue by kaname-png** [vime-js/vime#264]
# Bug Report

**Vime version:**
@vime/angular:  `^5.0.35`

**Provider:**

[] **Audio**
[x] **Video**
[] **HLS**
[] **DASH**
[] **YouTube**
[] **Vimeo**
[] **Dailymotion**

**Current behavior:**
Angular does not recognize the html elements of the module.

**Expected behavior:**
To be able to use HTML elements.

**Steps to reproduce:**
1. Install @vime/angular
2. import to AppModule on Imports
3. Try to use HTML elements

**Related code:**
```ts
import { NgModule } from '@angular/core';
import { VimeModule } from '@vime/angular';

@NgModule({
  imports: [VimeModule],
  exports: [VimeModule],
})
export class SharedComponentsModule {}
```

```ts
import { NgModule } from '@angular/core';
import { ComponentsSharedModule } from './components.module';

@NgModule({
  imports: [SharedComponentsModule]
})
export class AppModule{}
```

```html
<vm-player></vm-player>
```

**Other information:**
![image](https://user-images.githubusercontent.com/56084970/140625315-08aa1ef4-12e9-4362-b7c8-fc564e429ce9.png)

**Comment by izetrom** [comment]
hi, i'm having the same issue, anyone have some news about it ?
