### ISSUE TITLE
Vime is becoming Vidstack 🎉

### ISSUE THREAD

**Issue by mihar-22** [vime-js/vime#273]
👋 👋  👋 

## The Past

💡 You can skip to the next section if you're short on time.

I have some exciting news to share with anyone currently using Vime, or anyone interested in it! I thought I'd start by backtracking a little for transparency sake by covering what's been happening over the last year, and from there I'll talk a little about what's next for Vime. I promise only good things to come 😄 

I started Vime roughly mid-last year as I was exploring a potential startup idea around video. I was quite jittery and excited about the JS ecosystem and "newish" libraries such as [Svelte](https://svelte.dev), and I felt existing player libraries such as Video.js were a little outdated, bloated, and hard to customize. I was wondering, what if I rebuilt _something_ like [Video.js](https://videojs.com) but with newer technologies. Ultimately, that journey lead me to creating Vime. I was actually quite new to the frontend at the time of building it. I was coming over from mobile apps (iOS/Android), and working on the backend with Laravel (still love it to this day). Given all that, I'm sure most can see my frontend immaturity when looking at the Vime source. Everything was over-complicated, and I missed the mark on both the player API and UI customization. The integration wrappers are a bit of a mess, and the library simply became too hard to maintain.

After working on Vime for a few months, I ran into money problems because I neglected real-world responsibilities for a little too long 😓  I hated freelancing, and I was just starting to get excited about open-source, but that wasn't going to financially support me. I was actually down to my last $20, and my credit card was maxed out 😨  I had literally no idea what I was going to do. I usually have this feeling like things will work themselves out, but this time that feeling was shaky. 

Somehow by the luck of the gods, I woke up one day to a message on Discord. This is the exact message I read...

> Hi, Rahim! A pleasure to meet you. I came across Vime last week and was immediately impressed with the design and polish of such a young project. I am an engineer on the Video team at Reddit, and I too have been working on a new frontend video architecture to replace and consolidate our numerous existing video implementations. What strikes me about your project, besides its level of polish, is the incredible similarity of its architecture to that of my own. There are some subtle differences, but they generally have the same structure (controller/providers/ui), data flow (events up/context down/imperative provider API), etc, and the projects would appear to have very similar goals: HLS/Dash/third-party support, a11y, i18n, etc.
Your project is so similar, in fact, that I have started to discuss with my managers the possibility of incorporating your project. I would like to speak with you at your earliest convenience, either via text or video, to discuss the Vime project, your involvement, your team, and plans for future development. Please let me know when you come online when might be a good time to talk. 😃 Cheers! furf

Man... I ran so quickly to my wife excited out of my brain 🤯  I didn't know what this message meant but I had a good feeling. After a few more conversations I was contracted with Reddit to build a brand new player for them 👏  Honestly, I've had a wild year of meeting a few awesome friends, almost starting a startup, potentially working at [Mux](https://mux.com), almost getting into YC, and almost selling my player. Lots of almosts 😆  I made a bunch of mistakes, and spent my time in ways I shouldn't have looking back, but that's life I guess.

Over the year I built a [new player](https://github.com/vidstack/elements) that has been integrated into the new Reddit platform (only on mobile web at the moment, hopefully desktop next year). I also got to see some cool architectural work at Reddit around web components, and got to work on a brand new telemetry system for the player. I feel armed with all sorts of new ideas and knowledge 💪 

I'm saying all this to show why I eventually became disconnected from Vime and really let the project down. I was too far in one direction to really split my time effectively. It bothers me every day so much so, that I've made it my mission to continue exciting work around video on the web! The next section will dive more into what you can expect from here forward, and what the future looks like.

I'm excited for things to come, and would love for you to be a part of it with me!

## The Future

I'm embarking on building a new startup called [Vidstack](https://vidstack.io/) with some friends, and hoping to bring all of Vime over with me. No one left behind! The goal of Vidstack is to go beyond just the player, and provide a better workflow for frontend developers when working with video on the web. The general idea is to fill the void between "primitive" services such as Mux/AWS, and managed platforms generally targeting marketers such as Vimeo/YouTube. To be clear, we're not looking to replace them, but rather bring them together. We believe enabling multi-provider workflows is the future.

The ultimate goal is to make video more accessible for a whole wave of new frontend developers who are coming to the web. We love the simplicity of things like the Jamstack, and want to empower developers to be as productive as possible with video. 

**So here's where we're at:**

- Launched our [early access website](https://vidstack.io) this week.
- Prepared a bunch of placeholder repositories for exciting new projects on our [GitHub](https://github.com/vidstack).
- Updated the Vime discord server to [Vidstack](https://discord.gg/7RGU7wvsu9).
- Our [new video player](https://github.com/vidstack/elements) is up and running with pretty good internal documentation, but not ready for the public just yet. This is the same player that's running on the Reddit platform (mobile web specifically at the moment). I'm aware there's a few issues around the UX on Reddit, few blockers but I'll try to resolve it soon.

**What to expect in coming weeks:**

- Most likely a big announcement around another really popular open-source library joining Vidstack 😄 
- We'll initially be focusing all our energy on getting the new video player library into more hands. This means we need to review the internals, and get some documentation out.
- Start work on our initial MVP dashboard by gathering requirements and talking to all of you!
- Share a post around the new video player architecture and compare it to Vime.
- Begin reaching out to any users who [apply for early access](https://www.vidstack.io/early-access) to start figuring out how video is being used in the wild, and how we can make it better.
- Register the company soon and start looking for some angel investors who are either heavily involved in video on the web or the Jamstack community. If you're one reading this please reach out to me on rahim.alwer@gmail.com. Love to get a conversation going!

**Crazy future ideas:**

- Building our own serverless video encoding pipeline to attempt to bring costs down for everyone. We don't want to make money on encoding at all. We'll provide it at whatever it costs us. 
- A minimal [hls.js](https://github.com/video-dev/hls.js/) alternative, with a Rust based ABR engine. I have amazing ideas for reducing the initial load times ⏩  The first step is decoupling certain parts of the streaming engine and having them run in parallel through an async event bus. WASM and other stuff for ABR and so on. Still a WIP in my head.
- Really cool ideas around video player testing services. I don't want to share too much here yet, but it could be a big winner 💵 
- Start a podcast? We can start reaching out to prominenet figures in the development world that work closely with video, and see what their workflow is like. 

**What can you do?**

- Help us shape the product by letting us know what issues you're facing with video today. [Apply for early access](https://www.vidstack.io/early-access) and we'll reach out to you to organize a small chat.
- Follow us on [Twitter](https://twitter.com/VidstackHQ), we'll shoot our first post soon and start getting more active.
- Watch the releases of any repository on [GitHub](https://github.com/vidstack) to get notified when it's ready.
- Join our [Discord](https://discord.gg/7RGU7wvsu9) server and just say hi!

I hope you're as excited as I am for the future of video on the web! Feel free to leave your feedback, questions and ideas down below. Happy to fill in the blanks through the comment section 👇

**Comment by jbjhjm** [comment]
Congrats! I've to admit I was worrying about vime stability and future over the last months. But this does give a nice perspective for the future - likely with rock solid running code. 

Being a startup by ourselves we cannot invest huge sums atm, but if you allow for sponsoring e.g. through opensourcecollective we (and others hopefully) could support with a bit of cash?!

My 2c about crazy future ideas: I hope the main focus will stay on a well working modern video frontend.
For things like video hosting and encoding there already are many strong competitors around - as opposed to frontend.
So IMO there's much more need for strong frontend than for (another) strong backend.
Though, features like a player testing pipeline and hlsjs alternative sound like reasonable additions for modern video!

**Comment by mihar-22** [comment]
👋  @jbjhjm!

> Congrats! I've to admit I was worrying about vime stability and future over the last months. But this does give a nice perspective for the future - likely with rock solid running code.

Thanks! Ye I know I fell behind badly and it's been really frustrating for me to not be able to address a bunch of issues, simply because I'm somewhere else. I seriously can't wait to share the new library, so much awesomeness. I put a lot of energy and time ensuring the underlying architecture and code is rock solid. I promise you're going to love it 😄 

> Being a startup by ourselves we cannot invest huge sums atm, but if you allow for sponsoring e.g. through opensourcecollective we (and others hopefully) could support with a bit of cash?!

From what I've observed in the wild, this doesn't work unless you have a strong community and social presence. Some people with massively popular OS projects barely receive anything through those initiatives. I'd rather attempt to build a sustainable business behind the OS project, and support the work ourselves (ie: Vidstack). Hopefully we can build a community around Vidstack, which can in return help people contribute back to the project in various ways. It's been pretty hard for people to contribute to Vime because of the unnecessarily complex repo (my own mistakes).

> My 2c about crazy future ideas: I hope the main focus will stay on a well working modern video frontend.
For things like video hosting and encoding there already are many strong competitors around - as opposed to frontend.
So IMO there's much more need for strong frontend than for (another) strong backend.
Though, features like a player testing pipeline and hlsjs alternative sound like reasonable additions for modern video!

Couldn't agree more. Ye I don't want to give the idea that we're looking to chase building solutions around the service layer. Our sole differentiator is we're focused on all frontend aspects (application layer), and at the same time providing a low-code solution for managing, analyzing video through our dashboard (plus other stuff in the future). 

The only reason we would pursue those goals is if, a) we have the manpower to do so, b) it improves the overall Vidstack workflow for our users and their users (better UX/DX), c) and finally it can also reduce costs for everyone so we all win.

> One question, is vidstack based on the vime v5 code, or has it been rewritten from scratch and with different frameworks e.g. away from svelte etc?

It has been completely written from scratch (https://github.com/vidstack/elements). It still uses web components under the hood ([Lit](https://lit.dev/) instead of [Stencil](https://stenciljs.com/)). This opens up the opportunity for us to tackle SSR now 😄  

I guess in some part you're asking if we'll be doing framework-specific integrations like Vime? If we want to tackle SSR then I believe we'll have to. If we can avoid it to some degree then I'd love too, simply because web components are basically supported everywhere at this point (including React with the upcoming 18 release), and it's a fair bit of work maintaing integration wrappers.

This does not mean we're not considering how the player will be used in modern frameworks. For example, I recently refactored the player internals to use Svelte stores as a simple reactive primitive. You can access the store off the player and subscribe, or transform them into reactive streams with RxJS (mainly Angular).

_Svelte Example_

```svelte

<script lang="ts">
import { useMediaStore } from '@vidstack/elements';

let hlsPlayer;
const { paused } = useMediaStore(hlsPlayer);

$: if ($paused) {
  // ...
}
</script>

<vds-hls-player src="..." bind:this={hlsPlayer}>
  <!-- ... -->
</vds-hls-player>
```

At the minimum, we'll definitely have the basic tools (stores/hooks/composables/streams) you need to make video more fun in your chosen framework.

**Comment by jbjhjm** [comment]
Ah yes, I can see that lot's of thinking has been done here :)

Open Source funding: My personal experience is there's a what-comes-first problem. If there is a repo with unclear future, slow development and many unsolved, even uncommented issues, I am hesistating to spend money, cause it is likely wasted money.
On the other hand a project needs money for enough man power.
Then again there are repos that ask for money but have a good amount of fundings available and untouched for months or years, but development is still slow and chaotic. Ignored community PRs are a bad sign too.
It comes down to this: The devs need to be transparent, present and organized. And one side of community and devs needs to begin with trusting the other side.

Thanks for the short overview! The simple API/store access looks great. 
I love the web components approach and from my point of view it removes need for integration wrappers. When I got into vime, one of the first things I decided upon was to ditch the angular integration wrapper, enable allowance of web components and go with that. Less issues, less overhead. Of course that will only work if the framework supports web components.

However, the player elements may behave differently when used in different frameworks because of the way the framework renderers create/interact with dom. For example in angular environment, it sometimes happens that a vime subcomponents' request to connect to the parent/main vm player element store fails (e.g. "Uncaught (in promise): Could not find player for VM-VOLUME-CONTROL"). I tried to debug this but came to the conclusion I cannot fix that atm.
Back to Vidstack: Did you think about testing the components within different framework contexts? 
I believe this way it will be possible to find and eliminate a few more issues!

**Comment by mihar-22** [comment]
>  When I got into vime, one of the first things I decided upon was to ditch the angular integration wrapper, enable allowance of web components and go with that. Less issues, less overhead. Of course that will only work if the framework supports web components.

I believe most people followed this approach, it's the simplest take with the least amount of headache. I'd love to not bother with integration wrappers, I just need to weigh out the pros/cons of an SSR friendly library. Maybe there's a way to do it without wrappers via the Node `exports` feature.

> Did you think about testing the components within different framework contexts? I believe this way it will be possible to find and eliminate a few more issues!

I haven't got there just yet to think about it, but that's a good idea. We could have some integration tests run with Cypress to validate the library works as expected in some popular frameworks. This could start from installing the package, running builds and even down to playing the video succesfully.

**Comment by mihar-22** [comment]
For anyone who comes across this old announcement, we've taken a much simpler path forward and are simply focusing on open-source tools around video for frontend developers. We're still exploring paid products on the side, but we'd rather flesh them out through more discussions first. Join the Discord channel and let us know if you have anything in mind 😄 

You can find the new announcement in the pinned issues section.
