### ISSUE TITLE
How to get it working with svelte template

### ISSUE THREAD

**Issue by garrensmith** [vime-js/vime#29]
Hey, this project looks awesome. Thanks for building it. 
I'm struggling to get it to work with the basic [svelte template](https://github.com/sveltejs/template).

I did `npm install @vimejs/complete`. Then created a component:

```
<script>
  import { Player, FileProvider } from '@vime-js/complete';

  let player = new Player({
    src: "my-video.mp4",
    props:{
        providers:[FileProvider]
    }
  })

  const onPlayerMount = () => {
    // Interact with the player and plugins here.
  };
</script>

<Player
  on:mount={onPlayerMount}
  bind:this={player} 
/>
```

I then got an issue around not support scss. So I then did:

`npm install svelte-preprocess node-sass`

After that it complied but I'm now getting:
```
ReferenceError: process is not defineddebug.js:11:2
    app debug.js:11
    <anonymous> bundle.js:6919
```

Which seems to be this code:
```
if (
  // eslint-disable-next-line no-undef
  process.env.NODE_ENV === 'development'
  && window.console !== undefined
) {
  log = function vimeLog(...args) { console.log('[Vime]', ...args); };
  warn = function vimeWarn(...args) { console.warn('[Vime warn]', ...args); };
  error = function vimeError(...args) { console.error('[Vime error]', ...args); };
}
```

What am I doing wrong? Could you provide a basic example in the docs on running it in a Svelte project.

**Comment by mihar-22** [comment]
Hey @garrensmith apologies for the crappy experience. I forgot to document how to compile the player yourself which I'll write up today and I'll leave a link here once its done. You're really close, all your missing is installing `@rollup/plugin-replace` and adding it

```js
replace({ 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV) })
```

**Comment by mihar-22** [comment]
Hey @garrensmith the guide is up at https://vime-js.com/integrations/svelte. It's really simple and you've basically figured it out by this point but it's there if you need it. I've tested it myself for both Rollup and Webpack so you should be good to go. 

I'm closing this for now but if you're still struggling then feel free to reopen this.

Cheers!

**Comment by garrensmith** [comment]
@mihar-22 thanks. It's working now. Could you add a bit more to the guide around actually using the player. I had to set `useNativeControls={true}` to get the controls working. 
How do I load the default css and icons and use those as controls?

Also by the way I forgot to say. Great project. I think it has great potential.

**Comment by mihar-22** [comment]
Thanks @garrensmith for the kind words. You don't have to load any CSS or icons manually they're loaded via plugins. I'll definitely improve the docs as I get more time. I'm curious did you go through the [usage](https://vime-js.com/complete/usage) and [plugins](https://vime-js.com/plugins/getting-started) pages? The reason you have nothing showing is because you've installed no plugins. If you add the `Boot` plugin you'll get what you're looking for.

```html
<script>
  import { Player, FileProvider, Boot } from '@vime-js/complete';

  let player;

  const onPlayerMount = () => {
    // Interact with the player and plugins here.
  };
</script>

<Player
  src="my-video.mp4"
  plugins={[Boot]}
  providers={[FileProvider]}
  on:mount={onPlayerMount}
  bind:this={player} 
/>
```

**Comment by mihar-22** [comment]
Okay @garrensmith I've simplified some parts of the docs and added more links where needed based on the difficulties you were having. Hopefully it'll be much easier for others to get started. Thanks for providing feedback as you go 👍 

Updated docs: https://vime-js.com/complete/setup#setup

**Comment by garrensmith** [comment]
Awesome. Thanks

________________________________
