### ISSUE TITLE
Suggestion to increase the clickable area of time ranges

### ISSUE THREAD

**Issue by ryanatkn** [vime-js/vime#3]
This is such a cool project. Fantastic docs, great use of Svelte's flexibility and multiple builds, and this resonates with me:

> The idea behind Vime is we want you to control the player, not the other way around

Got a UX suggestion - right now the volume range click areas are nice and big, but the clickable area of the time ranges for the audio and video players are just a few pixels tall with a lot of dead area around them.

![hitbox1](https://user-images.githubusercontent.com/2608646/78962311-95dc4280-7ab9-11ea-8127-efc22cb274e5.png)

![hitbox2](https://user-images.githubusercontent.com/2608646/78962304-8fe66180-7ab9-11ea-93b2-8490c7c858ac.png)

![hitbox3](https://user-images.githubusercontent.com/2608646/78962308-92e15200-7ab9-11ea-9689-66c7e1bc87a5.png)

**Comment by mihar-22** [comment]
Hey @ryanatkn thanks for the awesome feedback, really appreciate it!  Ye you're right, nice catch. I'll get a PR out for that asap.

**Comment by ryanatkn** [comment]
Sweet you're welcome, don't rush on my behalf! Clearly a lot of work went into this.

**Comment by mehulmpt** [comment]
Sorry for hijacking the thread, but the player is great work indeed. I'm working on one of my sites right now changing the player to vime. Thanks for the project @mihar-22

**Comment by mihar-22** [comment]
Available for preview in the playground. I can't increase it too much at the moment without some better CSS magic. If you have any thoughts feel free to share :)

**Comment by ryanatkn** [comment]
Nice thank you! I'm looking forward to using Vime in a project - it might be several months before we're ready for it, but it looks like it fits our needs really well.
