### ISSUE TITLE
Errors on npm install @vime/react

### ISSUE THREAD

**Issue by DDeveloperBG** [vime-js/vime#312]
I use react v18.1.0 and after I run "npm i @vime/react" I receive errors like this: 
![image](https://user-images.githubusercontent.com/48260250/166710846-c82716af-fa66-44b1-a4ae-81870e6c8fb5.png)
Could this be because there is still no support for react v18?

**Comment by ialexanderbrito** [comment]
@DDeveloperBG Did you manage to resolve the error, I am facing this same issue?

**Comment by namchuai** [comment]
I also faced this issue..
