### ISSUE TITLE
Error: Cannot find module './Audio' NextJs

### ISSUE THREAD

**Issue by jsonpreet** [vime-js/vime#343]
![image](https://user-images.githubusercontent.com/26606638/202659051-b5032b95-5b2a-4670-87e0-650b7923467e.png)

Here I am getting this issue suddenly, Last night it was working fine.

Here what i am using:
```
"next": "13.0.2",
"@vime/core": "5.4.0",
"@vime/react": "5.4.0",
"react": "18.2.0",
```

```
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  experimental: {
    scrollRestoration: true
  },
  resolve: {
    extensions: ['.jsx', '.js', '.json', '.wasm'],
  },
  images: {
    minimumCacheTTL: 360,
    deviceSizes: [96, 128, 256, 384, 512, 640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
    ],
  },
}

module.exports = nextConfig
```

**Comment by jsonpreet** [comment]
solved

**Comment by nodgear** [comment]
> solved

You should tell us how you solved...

**Comment by ahmetskilinc** [comment]
Would like to know how this was solved.

**Comment by leighkendell** [comment]
Better late than never? For me I was able to resolve this issue by adding  '@vime/react' to the transpilePackages option in next.config: https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages @nodgear @ahmetskilinc

**Comment by nodgear** [comment]
> Better late than never? For me I was able to resolve this issue by adding '@vime/react' to the transpilePackages option in next.config: https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages @nodgear @ahmetskilinc

i recommend migrating to vidstack. the api is literally amazing.

**Comment by papitorcks** [comment]
Solution:

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@vime/react'],
}
 
module.exports = nextConfig
