### ISSUE TITLE
can't create vime-js tag on stackoverflow

### ISSUE THREAD

**Issue by nlebellier** [vime-js/vime#35]
Just to let you know that we can't post a question with vime-js tag... not allowed.

so i ask here : Very interested by your project. How to install and use it into a vue component ? A little help would be welcomed ?

cheers

**Comment by mihar-22** [comment]
Hey @nlebellier thanks for letting me know I've updated the docs so others can just raise an issue. At this time you can simply use [`ref`](https://vuejs.org/v2/api/#ref) to get a DOM node and then you can follow the JavaScript side of the documentation. 

```vue
<div ref="vime"></div>

<script>
import { Player } from '@vime-js/complete';

export default {
  mounted() {
    const target = this.$refs.vime;

    // From here you can just follow the docs.
    const player = new Player({ target });
  }
};
</script>
```



It'll be much easier once I release the Vue integration which I hope to have done in about 2 weeks.

**Comment by nlebellier** [comment]
> It'll be much easier once I release the Vue integration which I hope to have done in about 2 weeks.

Cool and thanks for your answer.
