### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by cynium** [vime-js/vime#38]
Great project! Would love to see some support for SSR frameworks like Svelte's Sapper. At the moment I can't find a way to get the standard or complete versions to work, as importing them in Svelte causes crashes due to attempts to access document and window when they are still unavailable (when rendering server-side).

The only thing that works right now is using @vime-js/lite imported from the @vime-js/standard installation. Interestingly, using lite when installed on its own does not work either.

**Comment by mihar-22** [comment]
Hey @cynium thanks! That's really weird, I'll dig into this once I have some time. Feel free to share any errors you're getting here which can help uncover the problem.

**Comment by cynium** [comment]
Here is the error I'm getting when trying to use @vime-js/standard:

`node_modules/@vime-js/standard/dist/standard.js:7694
	  if (apiMap[i][1] in document) {
ReferenceError: document is not defined`

**Comment by mihar-22** [comment]
Ahhh right ... that's coming from the [fullscreen api mapper](https://github.com/vime-js/vime/blob/master/packages/vime-standard/src/FullscreenApi.js). I'm pretty sure that should be the only leakage of document/window usage, so this should be an easy fix. I'll patch it tomorrow.

**Comment by mihar-22** [comment]
Oh I'll also need to double dig into why `@vime-js/lite` is failing SSR when installed on its own.

**Comment by cynium** [comment]
Sounds great, as standard has a few features that I'd really like to implement in this project.

I wasn't able to dig too deeply into why @vime-js/lite was failing SSR on its own -- it looked like it was trying to iterate over an empty or undefined array somewhere. I used the exact same boilerplate code from the usage guide in the docs with both.

**Comment by mihar-22** [comment]
I have no idea why it's not throwing any errors for me in a local Sapper environment. I actually want it to fail but it wont even though I know it definitely should ...

Anyway I'm working on this without any error guidance, seems like it's more work then I thought.   Window and document leakage in a bunch of places because I made the mistake of thinking reactive syntax `$:` was SSR safe. I'll see how it goes, hopefully I can get it done today.

**Comment by mihar-22** [comment]
I just released `1.6.1` and hopefully SSR works now. I couldn't get it to fail locally so love to hear if it works for you @cynium.

**Comment by cynium** [comment]
Nice work! Appreciate the quick digging into this. That seems to have fixed the SSR (no document errors anymore), but unfortunately now getting the same array error when trying to use the standard version of the player as I was previously when using the standalone lite player (as opposed to installing standard and importing lite from it):

`Error: {#each} only iterates over array-like objects.`

I created a separate route with just the vime player embed and the standard player works fine there. So it seems to be the result of some code interaction with my components... I took a quick look at the LitePlayer and StandardPlayer code but couldn't figure out what could be causing it... aside from the fact that I have a vime in a Video component, I'm not using any stores or props, just the boilerplate code with a hardcoded Vimeo ID.

**Comment by mihar-22** [comment]
Hm it's really hard for me to say without seeing the code or an example. I don't think that error is related to Vime because both the Lite and Standard players don't loop in the DOM unless you're using the `FileProvider` but you said you're using Vimeo. So I don't know how to recreate.

**Comment by cynium** [comment]
Did some more digging, and it seems to still be related to Sapper/SSR.

Here is a gist with the relevant code: https://gist.github.com/cynium/718e8751d52ead3fed672d2e5a5a2bcc

Basically, the index.svelte file has a `<script context="module">` which contains the code that is executed server-side. It's a simple API fetch to return a list of items.

Normally, the `items` const is passed to the client-side script block (brought in with the standard `export let items;`). When I import and use the lite player in my Vimeo.svelte component, everything works as described. But when I change it to standard, the items const is not passed from the SSR script module (my `Error: {#each} only iterates over array-like objects.` error was just the result of trying to loop over an undefined `items` array):

`<Routes> was created without expected prop 'items'`

Hope that's of some help.

**Comment by cynium** [comment]
Now we're getting somewhere:

`Error: &lt;Player&gt; is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:194:15)
    at /Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:325:19
    at Object.$$render (/Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:212:22)
    at /Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:1031:72
    at Object.$$render (/Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:212:22)
    at /Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:1217:43
    at each (/Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:183:16)
    at /Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:1210:7
    at Object.$$render (/Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:212:22)
    at /Volumes/Columbo/Stefan/Dropbox/Sites/culture-web/__sapper__/dev/server/server.js:1257:67</pre>`

**Comment by mihar-22** [comment]
Ohh ... it could be that your adding Vime as a dependency and not a dev dependency (installed as `npm install @vime-js/standard --save-dev`). When you do that Sapper treats it as an external dependency and doesn't compile it. I just threw up this Sapper guide today -> https://vime-js.com/integrations/sapper.

**Comment by mihar-22** [comment]
More information here -> https://github.com/sveltejs/sapper-template#using-external-components

**Comment by cynium** [comment]
Yup, that was it! (edited previous comment as you were replying). Learned a lot!

**Comment by mihar-22** [comment]
Awesome @cynium, happy it works now.

**Comment by blmhemu** [comment]
Am getting the following error in sapper :

```
const Audio = class extends HTMLElement {
              ^
ReferenceError: HTMLElement is not defined
    at Object.<anonymous> (/Users/hbollamreddi/git/rui/__sapper__/dev/server/server.js:2677:15)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

```

Observed a fix in : https://github.com/sveltejs/sapper/issues/774#issuecomment-663048738 (not yet tested it though)
But was wondering if it can be fixed in this codebase.

**Comment by mihar-22** [comment]
Hey @blmhemu, this is an old issue and the codebase has moved from Svelte to Web Components built with Stencil (even though we still support Svelte). Unfortunately at this time and to my knowledge there is no easy solution for making Web Components SSR friendly. The way to handle this is lazy loading via dynamic imports, the link you posted is a good solution.

**Comment by timothysu** [comment]
@mihar-22 is there a pattern for using the player store on the svelte bindings when lazy loading? I get `function called outside of component initialization` which makes sense.
