### ISSUE TITLE
Passing loop to an html5 video doesn't seem to work

### ISSUE THREAD

**Issue by antony** [vime-js/vime#40]
I'm importing Vime as follows

```
<script>
	  import { Player as VideoPlayer, FileProvider } from '@vime-js/standard'
</script>

<VideoPlayer src='https://qa.adaptive.delivery/api/v2/v/beyonk/q/site-assets/homepage-video.mp4' poster='https://qa.adaptive.delivery/api/v2/i/beyonk/q/site-assets/card/homepage-video.jpeg' providers={[ FileProvider ]} paused={false} autoplay={true} useNativeControls={false} loop={true} aspectRatio='16:9.6' />
```

And it seems like the `loop` attribute isn't getting passed to the video element (it's possible that you do the loop via javascript, so in that case, it's just not working at all.

**Comment by antony** [comment]
I also tried this:

```
 let player

  onMount(() => {
    const opts = player.getStore()
    console.log(opts.$loop)
  })
```

and it looks like loop is undefined.

**Comment by mihar-22** [comment]
Hey @antony unfortunately I couldn't recreate. I tried what you did in a quick svelte-app and it worked for me no matter what I did, the loop store was also defined. 

In your example `loop` was undefined because you were calling `console.log(opts.$loop)` instead of `console.log(opts.loop)`. If you want to auto-subscribe you could do

```js
let loop;

onMount(() => {
  ({ loop } = player.getStore());
});

$: console.log($loop);
```

**Comment by mihar-22** [comment]
I'm not sure how to help because it works in the playground as well. If you could maybe a share a little more about your project setup then I could dig into it.

**Comment by mihar-22** [comment]
Okay it has something to do with videos that are loaded externally, working on this now.

**Comment by mihar-22** [comment]
Okay @antony it's  not an issue with Vime but your server, [here is an explanation (https://stackoverflow.com/a/9549404). Hopefully that resolves it for you :)
