### ISSUE TITLE
Vimeo API timeupdate event no longer part of API

### ISSUE THREAD

**Issue by cynium** [vime-js/vime#41]
I wasn't seeing any playback progress data in the console from the onData function when testing out the Vimeo usage code here: https://vime-js.com/lite/usage

It turns out that the "timeupdate" event has been removed from the Vimeo API and replaced with "playProgress", so the docs should probably reflect that.

**Comment by mihar-22** [comment]
Awesome thanks for catching that @cynium, fixing it now.
