### ISSUE TITLE
Support auto aspect ratio based on video dimensions

### ISSUE THREAD

**Issue by secretcaptain** [vime-js/vime#42]
It would be great if we could get the height & width of the video from a provider (I know Vimeo returns vid dimensions with the embed, not sure about YouTube) and have a way to automatically set the wrapper to a matching aspect ratio, removing the black bars present in any video aspect ratio/wrapper mismatch...

**Comment by mihar-22** [comment]
Closing this in favor of `v2`, feel free to provide any feedback. I'm also going to keep a reference to address the issue in the next release.

**Comment by vruss** [comment]
@mihar-22 did this ever make it into v2?
