### ISSUE TITLE
Fullscreen is black on Safari (non native controls)

### ISSUE THREAD

**Issue by mehulmpt** [vime-js/vime#43]
If controls are set to non-native (Vime.js custom controls), when you try to go fullscreen on Safari, you get a black screen instead of video playing.

Repro:

1. Open https://playground.vime-js.com/?path=/story/complete--video-file in Safari
2. Set `useNativeControls` to checked
3. Try to go full screen

**Comment by mihar-22** [comment]
Thanks for letting me know @mehulmpt. Fixed in the latest release `1.6.3`.
