### ISSUE TITLE
How to externally start to play?

### ISSUE THREAD

**Issue by miracle2k** [vime-js/vime#45]
I am looking for something like `player.play()`. The docs for the lite player suggest `player.sendCommand()` and via Github code search I could identify `player.sendCommand(playVideo)`. But that is not available on the "complete" player package.

Neither does the following work: `player.getStandardPlayer().getLitePlayer().sendCommand()` - `getLitePlayer()` does not exist here.

**Comment by mihar-22** [comment]
Hey @miracle2k when using `@vime-js/complete` you have access to all the `@vime-js/standard` properties. What you're looking for is `player.paused = false`.

Standard API -> https://vime-js.com/standard/api/player

**Comment by miracle2k** [comment]
Thanks. I saw the read-only `played` property and assumed that the way to do it would not be through properties, and tried to find a solution via methods.
