### ISSUE TITLE
Delay after clicking with `ClickToPlay`

### ISSUE THREAD

**Issue by silllli** [vime-js/vime#46]
Using the `ClickToPlay` plugin and not the native controls causes a small delay between the click on the video and the video pausing or playing.

When clicking the play button, everything is fine.

**Comment by mihar-22** [comment]
Hey @silllli, ye I put a small delay to help differentiate between a single click to play and double click for fullscreen. The delay is definitely noticable and I need to smooth it out, I'll address this in the next release.

**Comment by silllli** [comment]
Thank you for getting back @mihar-22. I hope it’s a rather simple fix!

**Comment by mihar-22** [comment]
Closing this in favor of `v2`, feel free to provide any feedback. I'm also going to keep a reference to address the issue in the next release.
