### ISSUE TITLE
HlsProvider: video not loading when src is changed

### ISSUE THREAD

**Issue by mightymercado** [vime-js/vime#48]
How do I change the src of the video after it's already been setup? I tried src and bind:src in svelte but they both freeze the player.

**Comment by mihar-22** [comment]
The `src` prop should just work. I quickly tested switching mp4 videos and it was working. It might have something to do with updating Svelte to the latest version. 

If you can just tell me what version of Svelte you're using, and what type of source you are switching, whether it's a YouTube video to a YouTube video, or a file to something else, then I can dig a little deeper in the issue.

**Comment by mihar-22** [comment]
Though I discovered some strange bug doing this which causes tooltips to position incorrectly after changing the source.

**Comment by mightymercado** [comment]
@mihar-22 Then I believe it could be a provider-specific issue. I'm using HLS / m3u8 file. Can you test on your end?

**Comment by mihar-22** [comment]
Ah ye it's when switching between HLS (`.m3u8`) files. At the moment when changing the `src` the provider is calling `hls.loadSource(newSrc);` which is correct. I think some updates is causing a state change to mess with player. This usually happens when calling `media.load()` on the underlying HTML5 video player instance. If I have some time tonight I'll look into it.

**Comment by mihar-22** [comment]
Closing this in favor of `v2`, feel free to provide any feedback. I'm also going to keep a reference to address the issue in the next release.

**Comment by Enigma10** [comment]
@mihar-22 This was not working in `v5`. I had to do `hls.loadSource(newSrc)` to get update.

**Comment by marty0678** [comment]
> @mihar-22 This is not working in `v5`. I had to do `hls.loadSource(newSrc)` to get update.

Thank you for this. I was struggling with this today and confused why the src wasn't updating. For others that encounter this issue, I pulled the HLS object from the HLS's element for reference.

```
// Vue example
const vimeHls = this.$refs.vimeHls
vimeHls.$el.hls.loadSource(this.src)
```
