### ISSUE TITLE
Question: how to initialise Youtube parameters like "rel" or "showInfo"

### ISSUE THREAD

**Issue by yaaax** [vime-js/vime#50]
Hi there,

I'm wondering if it's possible to pass parameters to the player like :

- rel = 0
- showInfo = 0
- ...

See https://developers.google.com/youtube/player_parameters#Parameters

Thanks for your help.

**Comment by mihar-22** [comment]
Hey @yaaax you can pass them via the `params` prop. It should work regardless of the player you're using. You can adapt the following example for Svelte

```js
// ...

const player = new Player({
  target,
  props: {
    // ...
    params: {
      rel: 0,
      showInfo: 0
    }
 }
});
```

**Comment by yaaax** [comment]
Perfect. Thank you!

**Comment by mishu-bkash** [comment]
How to use these parameters for YouTube component?

Any kind of hep is highly appreciated.
