### ISSUE TITLE
how do I load a video? 

### ISSUE THREAD

**Issue by chovy** [vime-js/vime#52]
Docs are ambiguous at best.

```
<script>
  import { onMount } from "svelte";
  import { Preview } from "@vime-js/preview";

  let preview;

  export let src;

  onMount(() => {
    /**
     * If you need to call any methods, you have access
     * to the preview instance here.
     **/
  });
</script>

<Preview bind:this={preview} src={src} />

```

`<VideoPlayer src='/video.mp4' />`

THis doesn't work

**Comment by mihar-22** [comment]
Hey @chovy, I'm not sure what player you're using and I can't see all your code. There's an [example](https://vime-js.com/standard/setup#setup) for both the Standard and Complete player that shows how to do it. It won't work if you haven't loaded any providers. Follow the link and you should be fine. There's also an additional [loading media guide](https://vime-js.com/guides/loading-media) that can help.

**Comment by mihar-22** [comment]
Side note just incase, the `@vime-js/preview` package is not for loading a video player. As it says in the docs:

> Preview is used to display a thumbnail. If your src points to an external provider then the thumbnail is automatically loaded. If you'd like to know how it compares to other options then see the getting started page.

You can go here for more information on the different components available: https://vime-js.com/getting-started

**Comment by chovy** [comment]
ahh ok.
