### ISSUE TITLE
VimeoProvider: after seek, currentTime doesn't update

### ISSUE THREAD

**Issue by Injae-Lee** [vime-js/vime#53]
Unlike other providers, when playing a video through VimeoProvider, the video plays fine after seek but the currentTime value of store does not change.
It can be reproduced in the playground.

**Comment by mihar-22** [comment]
Thanks for reporting the bug @Injae-Lee. Everything should be fixed in the latest release `1.6.5`.

**Comment by Injae-Lee** [comment]
Thanks!
