### ISSUE TITLE
Can't get @vime-js/complete example to work

### ISSUE THREAD

**Issue by FranzWegner** [vime-js/vime#54]
I'm very new to Svelte but I'm eager to try some things in conjunction with Vime JS.
I'm trying to run the example from here: https://vime-js.com/complete/setup
I just replaced the lines in App.svelte (from the standard svelte template) with the code mentioned in the set-up guide.
I also followed these steps: https://vime-js.com/integrations/svelte

 rollup.config.js excerpt:
```
import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import replace from '@rollup/plugin-replace';
import sveltePreprocess from 'svelte-preprocess';

const production = !process.env.ROLLUP_WATCH;

export default {

    input: 'src/main.js',
    output: {
        sourcemap: true,
        format: 'iife',
        name: 'app',
        file: 'public/build/bundle.js'
    },
    plugins: [
        svelte({
            preprocess: sveltePreprocess(),
            // enable run-time checks when not in production
            dev: !production,
            // we'll extract any component CSS out into
            // a separate file - better for performance
            css: css => {
                css.write('public/build/bundle.css');
            }
        }),
        replace({ 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV) }),
        // If you have external dependencies installed from
        // npm, you'll most likely need these plugins. In
        // some cases you'll need additional configuration -
        // consult the documentation for details:
        // https://github.com/rollup/plugins/tree/master/packages/commonjs
        resolve({
            browser: true,
            dedupe: ['svelte']
        }),
        commonjs(),

        // In dev mode, call `npm run start` once
        // the bundle has been generated
        !production && serve(),

        // Watch the `public` directory and refresh the
        // browser on changes when not in production
        !production && livereload('public'),

        // If we're building for production (npm run build
        // instead of npm run dev), minify
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
};
```
Obviously I also replaced the media source with a local mp4 file. When starting the dev server now with "npm run dev" and switching to the url in Chrome the page is stuck in a loop (page is loading) and isn't rendering anything (Elements tab in Chrome Dev Tools is empty, Network tab shows livereload.js?snipver=1 as pending). 

@vime-js/standard works fine for me. So it seems there is an error in the communications between @vime-js/complete and my edited rollup.config.js.

Can you please guide me to my mistake? :)

**Comment by mihar-22** [comment]
Hey @FranzWegner, it's super cool you're learning Svelte and trying Vime out. Unfortunately, I don't have time to reproduce but your Rollup configuration is all good. By the sounds of the error this has something to with `sirv`or `livereload` but it hasn't happened before on my end ... so I'm really not sure. I'm assuming you've installed `node-sass`. Could it be your `mp4` file is corrupted?

**Comment by FranzWegner** [comment]
Thank you for your comment. I'm still trying to figure it out. node-sass is installed and the mp4 is not the problem. Just for the sake of it I'm just using "null" as src now.
I tried to host online the sample application so I can strike out my own network as the problem. You can check it out here: https://svelte-test-7b947.web.app/

I'm also uploading my complete source code so maybe you can try if you encouter the same problems now? 
https://fil.email/q2eGWmqi

Additionally I tried using the webpack template (https://github.com/sveltejs/template-webpack) and create the sample Vime application. Installed and configured exactly as suggested here: https://vime-js.com/integrations/svelte
When running the "npm run dev" it basically can't handle any .svelte files as I understand.

```
ERROR in ./node_modules/@vime-js/standard/src/providers/Hls.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <File
|   {crossorigin}
|   {player}
 @ ./node_modules/@vime-js/standard/src/providers/index.js 5:0-44 11:0-23
 @ ./node_modules/@vime-js/standard/src/index.js
 @ ./node_modules/@vime-js/complete/src/index.js
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js

ERROR in ./node_modules/@vime-js/standard/src/providers/Dash.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <File
|   {crossorigin}
|   {player}
 @ ./node_modules/@vime-js/standard/src/providers/index.js 6:0-46 12:0-24
 @ ./node_modules/@vime-js/standard/src/index.js
 @ ./node_modules/@vime-js/complete/src/index.js
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js

ERROR in ./node_modules/@vime-js/standard/src/providers/YouTube.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <LitePlayer
|   {src}
|   {params}
 @ ./node_modules/@vime-js/standard/src/providers/index.js 2:0-52 9:0-27
 @ ./node_modules/@vime-js/standard/src/index.js
 @ ./node_modules/@vime-js/complete/src/index.js
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js

ERROR in ./node_modules/@vime-js/standard/src/providers/Dailymotion.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <LitePlayer
|   {src}
|   {params}
 @ ./node_modules/@vime-js/standard/src/providers/index.js 4:0-60 13:0-31
 @ ./node_modules/@vime-js/standard/src/index.js
 @ ./node_modules/@vime-js/complete/src/index.js
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js
```
Etc. etc.

Download complete source code: https://fil.email/wJWEwvic

Maybe you can send me a sample working project of your own? Maybe it's something with my local machine (Windows 10) and/or Node version.

**Comment by mihar-22** [comment]
I was working on fixing some small bug quickly today and I realized the UI locking up as well. I'm pretty certain this has to do with using the latest version of `svelte`. Because it started happening exactly then. I'll let you know more as I dig into it but it's very hard to debug because everything just locks up.

**Comment by mihar-22** [comment]
Ye it's definitely Svelte related. The library works up until `svelte@3.22.3` and breaks on `3.23.0`. It has to do with using an `#each` loop with `svelte:component` which happens inside `PluginsManager.svelte`. I'll see if I can resolve otherwise I'll raise an issue.

**Comment by mihar-22** [comment]
Okay awesome fixed! Something changed with how Svelte was exporting modules. Everything should work just fine now @FranzWegner. Sorry you wasted a lot of time and had a crappy experience. I hope to make this all much better in Vime 2!

**Comment by FranzWegner** [comment]
Awesome, it works now! Thank you for your efforts :)
