### ISSUE TITLE
Can't use Vime in sapper application

### ISSUE THREAD

**Issue by georgeciubotaru** [vime-js/vime#55]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/8217518/87060899-b8ded580-c213-11ea-903e-03923e6babf7.png">

After I digging the code, found the issue

```
export const ORIGIN = (window.location.protocol !== 'file:')
  ? `${window.location.protocol}//${window.location.hostname}`
  : null;
```
Here you didn't check for `IS_CLIENT`.

**Comment by mihar-22** [comment]
Nice catch @georgeciubotaru, thanks for that. Everything should be working fine now in `1.6.5`.
