### ISSUE TITLE
Autoplay not working - Google Chrome desktop browser on Windows

### ISSUE THREAD

**Issue by zlatevbg** [vime-js/vime#56]
I'm using Vanilla JavaScript.
Here's my setup:

```
const player = new Vime.Player({
    target,
    props: {
        src: '/video.mp4',
        providers: [Vime.FileProvider],
        autoplay: true,
        muted: true,
        loop: true,
    }
});
```

The above code works in the latest desktop browsers on Windows: Firefox & Edge, but not in the latest Chrome.

The result from `canAutoplay` is `false` while the result of `canMutedAutoplay` is `true` but still the video doesn't autoplay.

Maybe the `muted` attribute needs to be set on the video tag?

**Comment by mihar-22** [comment]
I'm rebuilding this library for the `v2` release, I'll keep this as a reference to make sure it works.
