### ISSUE TITLE
How to add new buttons to player?

### ISSUE THREAD

**Issue by FranzWegner** [vime-js/vime#57]
I'm guessing that my question will be answered with this: https://vime-js.com/guides/custom-controls

But in general I'd still like to know what's the recommended approach for extending the player API.
In particular I want to the extend the mobile player by having a -10 and +10 second seek next to the pause/play button in the center and also an extra button at the top right with custom functionality (in my case switching to a new Youtube video and keeping the current time, like a language selector).

I have the logic already done (at the moment just with additional buttons below the player), so I'm just looking for the cleanest way to add custom buttons to the player and assigning functions to them.

**Comment by mihar-22** [comment]
These two references will guide you:

- https://vime-js.com/plugins/api/controls
- https://github.com/vime-js/vime/blob/master/packages/vime-complete/src/plugins/controls/DefaultControls.svelte

I'd recommend that if you have time then you can just wait for Vime 2. Everything is going to change and this process will be much easier. Looking at ~2-3 week timeframe.

**Comment by FranzWegner** [comment]
Thank you, I'll wait for Vime 2 then :)
