### ISSUE TITLE
Vime doesn't work after version update (v1.6.5)

### ISSUE THREAD

**Issue by Injae-Lee** [vime-js/vime#58]
After `@vime-js/complete` was updated, `Module not found: Error: Can't resolve '@vime-js/complete'` error occured.
In my opinion, the reason is that unlike previous versions, there are only production-built files(`.min.js`) in this version's `dist` folder.

**Comment by mihar-22** [comment]
That's completely my fault, I ran the wrong build command ... All fixed in `1.6.6`.
