### ISSUE TITLE
Html5 Support

### ISSUE THREAD

**Issue by CodeDruid13** [vime-js/vime#60]
Been going through docs and my use case is very specific. I needed to use the player as a html5 video player and i can't find a  setup for it. Any guide?

**Comment by mihar-22** [comment]
The `FileProvider` is for loading videos via `html5`. The setup guide [here](https://vime-js.com/complete/setup#setup) shows how to setup the player to use files.  The [loading media guide](https://vime-js.com/guides/loading-media#file) shows different ways you can load files. That should put you in the right direction.
