### ISSUE TITLE
Can't find any documentation on how to play a dash video in angular

### ISSUE THREAD

**Issue by connois** [vime-js/vime#64]
Hello,

I'm trying to find a documentation or an example on how to play a dash video using vime in Angular 9.

Can someone help me with an example ?

Thanks

Arnaud

**Comment by mihar-22** [comment]
Hey @connois, I'm still currently working on the documentation, it's not "officially" released yet. I can only offer you the Angular example (https://github.com/vime-js/vime/tree/master/examples/angular) which should get you going. Keep an eye out, the documentation should be ready by the end of the week.

**Comment by mihar-22** [comment]
Oh you also have the component API for the Dash provider if you're eager to get going.

Dash Provider: https://vimejs.com/components/providers/dash/api
