### ISSUE TITLE
Svelte wrapper

### ISSUE THREAD

**Issue by anito** [vime-js/vime#65]
Hi, awesome work!
Just switching from v1 to v2.
For V2 I just wanted to write my own vime/svelte wrapper using vime/vue as a blueprint. However I get stuck at the compile step (npm build) no matter which of the currently existing ones (react, angular, vue...) I'm trying to compile. Errors are thrown in the index.ts where the path to components "./components" can not be found. Am I missing anything? Thx

**Comment by mihar-22** [comment]
Hey @anito it's failing because you have to run the build command from `@vime/core` which will auto-generate the components files for `@vime/{react,vue,angular}`. They are generated by [stencil-ds-output-targets](https://github.com/ionic-team/stencil-ds-output-targets). I thought about spending time writing a wrapper as well but I'm not sure because the benefit is super minimal, instead I've created a `usePlayerStore` option for easier integration which you can see [here](https://github.com/vime-js/vime/blob/wip/examples/svelte/src/App.svelte) and [here](https://github.com/vime-js/vime/blob/wip/examples/svelte/src/TapSidesToSeek.svelte). What do you think? Is the store option enough? Is there any specific reason you'd like a Svelte wrapper?

**Comment by anito** [comment]
Hi @mihar-22,
thx a lot. I see you merged branch wip into master....
So after a little tweaking (had to manually copy @vime/media into "examles/svelte/node_modules" cause it's private?) I was able to get the "example/svelte" up and running. Unfortunately I had to temporarily quit playing with it for now. As soon as I find the time tonight I will for sure bother you with may be more detailed questions if there should arise any ;)

I'm completely new to native js modules and I wonder how your <vime-*> tags get to be known to the application (last time I tested this I ran into issues - <vime-*> tags behaved like unknown tags to the browser although the deferred script module in the index.html was present. So I started thinking I need to have a @vime/svelte wrapper to make it work... But I'm sure sth. else I did was wrong. So (lazy) loading the @vime/core@latest/dist/vime/vime.esm.js is supposed the way to go? Or would import * @vime/core be also an option?

Why svelte: short answer is I'm independent (whereas big companies aren't). Plus svelte is highly reactive per se, with no complicated equations that says to do so. No framework code in the client just pure vanilla script that only serves the very specific needs of the app. Very simple to use.

Thx

**Comment by anito** [comment]
Hi @mihar-22,
so I spend some time (always starting over using a fresh clone) to figure out what needed to be done before the svelte example can get successfully started. Here's what I came up with:

#### Running svelte example
**/**
1.  npm i pnpm
2. npm run setup

**/packages/core**
1. npm i
2. npm run build

**/packages/svelte**
1. npm i
2. npm run build

**/examples/svelte**
1. npm i pnpm
2. **do not** npm i !!! (the @vime/media will not be found)
3. npm run setup
4. npm run serve

#### Installing vime v2 into my project (I'm using Sapper build on top of svelte, supporting SSR ...)

Fails in both cases:

Dev mode:
GET http://localhost:3000/node_modules/@vime/core/dist/vime/index.esm.js net::ERR_ABORTED 404 (Not Found)

or when using CDN:
TypeError: Cannot read property 'parentElement' of null
    at t (p-6043e4a2.js:1)
    at j.hasCustomPoster (p-0b18b50d.entry.js:1)
    at j.render (p-0b18b50d.entry.js:1)
    at Y (p-9ca20aae.js:1)
    at X (p-9ca20aae.js:1)
    at p-9ca20aae.js:1
    at oe (p-9ca20aae.js:1)
    at Q (p-9ca20aae.js:1)
    at Array.<anonymous> (p-9ca20aae.js:1)
    at ve (p-9ca20aae.js:1)

p-9ca20aae.js:1 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
    at L (p-9ca20aae.js:1)
    at A (p-9ca20aae.js:1)
    at p-9ca20aae.js:1
    at N (p-9ca20aae.js:1)
    at p-9ca20aae.js:1
    at X (p-9ca20aae.js:1)
    at p-9ca20aae.js:1
    at oe (p-9ca20aae.js:1)
    at Q (p-9ca20aae.js:1)
    at Array.<anonymous> (p-9ca20aae.js:1)

I would love to just be able using the vime-player module just the way I deal with code in all my existing components:
import {....} from '@vime/core' instead of importing scripts directly from public/index.html (or in case of sapper: src/template.html)

Right now I'm quite lost in space, all seems quite complicated to me.

Any suggestions how I could proceed? Thx

**Comment by mihar-22** [comment]
Hey @anito unfortunately I don't really understand what you're trying to do. The instructions for how to run the Svelte example are in the directory:

## Usage

Install [pnpm](https://pnpm.js.org/en/installation) and then run the following commands to serve the example.

```bash
# This will take some time (~480MB), but you only have to do it once.
$: git clone https://github.com/vime-js/vime

$: cd vime/examples/svelte

$: npm run setup

$: npm run serve
```

Are you saying this doesn't work for you? You need `pnpm` installed on your machine not in the directory.

**Comment by mihar-22** [comment]
In regards to using it in your project, you simply throw in the script in your `index.html` and setup it up as I did and it should work. I'll try a fresh project and see if I get the error as well. Don't worry I created Svelte bindings, they should up and running very soon, just ironing it out today. You'll be able to do `import { x } from '@vime/svelte'`.

**Comment by anito** [comment]
Hi @mihar-22,
so I spend some time (and always starting over again using a fresh clone) to figure out what needed to be done before the svelte example can be successfully started. Here's what I came up with:

**/**
1.  npm i pnpm
2. npm run setup

**/packages/core**
1. npm i
2. npm run build

**/packages/svelte**
1. npm i
2. npm run build

**/examples/svelte**
1. npm i pnpm
2. **do not** npm i !!! (the @vime/media will not be found)
3. npm run setup
4. npm run serve

**Comment by mihar-22** [comment]
Ye I understand but you shouldn't have to do that. Can you share what error you get when you try to do it following the steps I listed above?

**Comment by anito** [comment]
Hi @mihar-22,
for the very start I just want to get rid of any errors thrown on this [page](https://physio.doojoo.de/videos)  (user: test@webpremiere.de pass:test)
Implementation is kept very basic. It doesn't make use of @vime/svelte just trying to implement @vime/core correctly. You might look at this [here](https://github.com/anito/physio-dips-app/blob/master/src/routes/_components/_MediaPreview.svelte#L109)  or [here](https://github.com/anito/physio-dips-app/blob/master/src/routes/_components/_VimePlayer.svelte#L25)

May be you find the time. Thx

**Comment by anito** [comment]
Hi @mihar-22,
I seemed to be able to locate the cause of my specific problem. I'm kept trying to reactively change src/poster. In my specific case, the players src/poster are promises, that before resolved, are only placeholders and hence need to be changed when those actual and encrypted paths return from the server (That way I'm trying to protect my clients footage from abuse).
I think that for now the only acceptable solution would be to create my own component.
In case I have missed anything, I'd be happy to get any advices from you, thx.
