### ISSUE TITLE
PlayerProps undefined

### ISSUE THREAD

**Issue by anito** [vime-js/vime#66]
Hi @mihar-22,
I'm using sapper/svelte and the most recent @vime/core at the time of this write.

ISSUE
when the player store [on this video page](https://physio.doojoo.de/videos) first gets created `PlayerProps` are populated as they should. However when navigating [away](https://physio.doojoo.de/images) and returning to [previously visited videos page](https://physio.doojoo.de/videos), component will render first with some PlayerProps being `undefined` and hence the error `Player.<PlayerProp> is readonly. Do not attempt to change it.` are thrown.

Affected Props are the following:
- `Player.errors` (if debug mode true)
- `Player.playbackRates`,
- `Player.playbackQualities`,
- `Player.languages`,
- `Player.translations`

None of the above internal player props where changed on my side.

`PlayerState` immediately thereafter (and obviously within the same `componentWillRender` call), is populated correctly again.

Please have a look [at this page](https://physio.doojoo.de/videos) and check for errors in the console. Note that all video components are in debug mode. @vime/core was also slightly changed for this issue to debug.

You can see my implementation of `vime-player` [here](https://github.com/anito/physio-dips-app/blob/master/src/routes/_components/_VideoPlayer.svelte)

Thx

**Comment by mihar-22** [comment]
Hey @anito thanks for bringing up this issue. In the latest release no errors are thrown anymore for writing to readonly properties, it will only log a warning to the console. I think this issue might be resolved in the latest release `4.1.0`. Please create a new issue if anything of this type is still happening.
