### ISSUE TITLE
Can't play hls(m3u8) video

### ISSUE THREAD

**Issue by demonskp** [vime-js/vime#70]
Maybe I set a wrong config?

example:
https://codesandbox.io/s/trusting-margulis-nvrum?file=/src/App.js

This video can be played normally on the test page of hls.js。

Hope to get a clearer demo

**Comment by demonskp** [comment]
i set one more         <VimeVideo>

**Comment by mihar-22** [comment]
Hey @demonskp! Here's the working version: https://codesandbox.io/s/elegant-williams-90iuq?file=/src/App.js.

**Comment by demonskp** [comment]
3Q u，This is my mistake, did not look at the example carefully。
