### ISSUE TITLE
Video not centered when aspect ratio changed

### ISSUE THREAD

**Issue by wplit** [vime-js/vime#77]
This only happens when the 'controls' property on the player is not added.

See the screenshots with controls property removed and then added, when using a 21:9 ratio. Notice in the first screenshot, the video isn't centered and the black outline still visible.

<img width="400" alt="Screen Shot 2020-10-01 at 12 11 53 pm" src="https://user-images.githubusercontent.com/43051571/94758117-a83b9700-03df-11eb-8a2b-d0cacb183338.png">
<img width="400" alt="Screen Shot 2020-10-01 at 12 12 50 pm" src="https://user-images.githubusercontent.com/43051571/94758119-abcf1e00-03df-11eb-9417-e36464dc172f.png">

**Comment by mihar-22** [comment]
Thanks for bringing it to my attention @wplit 👍  I'll dig into this as soon as I can.

**Comment by wplit** [comment]
Update - it doesn't seem to be happening with youtube. and sometimes with vimeo it looks fine with the poster image, until you click play https://www.loom.com/share/bfb2a277915e427dadc19a3143c184f2

**Comment by mihar-22** [comment]
I could only re-create this issue with the Vimeo provider. Is that the only provider breaking for you at the moment?

**Comment by wplit** [comment]
tbh I only tried Vimeo, Youtube, and the vime-video player. but yes, it was only on Vimeo where i spotted this.

**Comment by mihar-22** [comment]
Fixed and is being released via the CI, should be ready in <10 minutes.

**Comment by mihar-22** [comment]
Thanks again for helping me spot these issues, I appreciate it :)
