### ISSUE TITLE
Vime does not work when bundling with Rollup

### ISSUE THREAD

**Issue by RailgunWinjoy** [vime-js/vime#82]

**Comment by RailgunWinjoy** [comment]
I can't get it work on my Svelte-Sapper project with the given example

` <VimePlayer
  theme="dark"
  style="--vm-player-theme: #e86c8b;"
>
  <VimeVideo
    crossOrigin
    poster="https://media.vimejs.com/poster.png"
  >
    <source 
      data-src="https://media.vimejs.com/720p.mp4" 
      type="video/mp4"
    />
    <track 
      default 
      kind="subtitles" 
      src="https://media.vimejs.com/subs/english.vtt" 
      srclang="en" 
      label="English" 
    />
  </VimeVideo>
  
  <VimeDefaultUi />
</VimePlayer>
<script>
import { VimePlayer, VimeVideo, VimeDefaultUi } from '@vime/svelte';
 `

**Comment by mihar-22** [comment]
Hey @RailgunWinjoy! If you're using the Sapper rollup template it won't work, not sure why exactly at the moment but you need to use Webpack. If you're using Webpack and it's still not working I'll need an example repo or something because it works on my end.

**Comment by RailgunWinjoy** [comment]
Thankyou i'll try it now

**Comment by RailgunWinjoy** [comment]
Yes You're right! After changed it into Webpack it works

**Comment by mihar-22** [comment]
Awesome! I should add a note about this in the Svelte installation instructions for other users.

**Comment by RailgunWinjoy** [comment]
Thank you for the fast response !

Btw is this support automatically save/restore play times

**Comment by mihar-22** [comment]
Not at the moment @RailgunWinjoy, I'll need to create a plugin for that which I've opened an issue for ([Local Storage Plugin](https://github.com/vime-js/vime/issues/36)).

**Comment by RailgunWinjoy** [comment]
Cool ! This player is awesome better that the Vue one i used

**Comment by JohnRSim** [comment]
Is the issue with rollup due to output as IIFE where you cannot dynamically do imports...
You have to export as AMD or SystemJS or use this plugin - 
https://github.com/surma/rollup-plugin-off-main-thread
