### ISSUE TITLE
Allow VideoJS "Playback Tech" plugins?

### ISSUE THREAD

**Issue by tomByrer** [vime-js/vime#84]
I was thinking of writing my own video player but use [VideoJS's Playback plugins](https://docs.videojs.com/tutorial-tech_.html) instead of writing my own....

**Comment by mihar-22** [comment]
I'm not sure I completely understand the question, I understand it as you want to add a new provider and are looking at how Videojs handles adding new ones and asking if you could do the same with Vime?

I'd need more information on what you're trying to achieve but I'll just note that 'Playback Tech' are known as 'Providers' in Vime. They both attempt to perform the same goal of delegating loading players and controlling playback to a component with a standard interface. You can compare the [HTML5 playback tech](https://github.com/videojs/video.js/blob/main/src/js/tech/html5.js) in Videojs with [Vime](https://github.com/vime-js/vime/blob/master/packages/core/src/components/providers/file/file.tsx) and you'll see a lot of overlap. Videojs extends the [Tech](https://github.com/videojs/video.js/blob/8e5a1af82637e1c910a3336bca1d63509e9ea2cc/src/js/tech/tech.js) class, and Vime implements the [MediaProvider](https://github.com/vime-js/vime/blob/master/packages/core/src/components/providers/MediaProvider.ts) interface.

If you can provide more information I can hopefully help you better 👍

**Comment by tomByrer** [comment]
Since VideoJS has more video provider plugins, I hope to have Vime use those "Tech" plugins, to help quickly expand the number of media sources Vime can use.

Does that help?  Sorry I wasn't so clear.

**Comment by mihar-22** [comment]
Ah okay you're asking for Vime to be able to handle Videojs playback tech. It's not a bad idea that I'll think about but at at this time I don't think Videojs actually supports more providers than Vime that have first-class support. The community plugins in Videojs are not maintained such as YouTube and so on. Off the top of my head I think Vime supports more providers than Videojs. Is there a specific provider missing you are after?
