### ISSUE TITLE
Multiple sources/qualities?

### ISSUE THREAD

**Issue by aolko** [vime-js/vime#86]
How do i handle multiple `<video>` sources of different qualities?

```
<vime-player id="player">
  <vime-video cross-origin>
    <source data-src="https://filesamples.com/samples/video/mp4/sample_1920x1080.mp4" type="video/mp4" label="1080p">
    <source data-src="https://filesamples.com/samples/video/mp4/sample_3840x2160.mp4" type="video/mp4" label="4K">
  </vime-video>

  <!-- Loads the default Vime UI. -->
  <vime-default-ui />
</vime-player>
```
[**bin**](https://jsbin.com/vusowufapa/edit?html,output)

Upd: Seems like the quality settings are youtube/vimeo exclusive. Please reflect that in the docs.

**Comment by mihar-22** [comment]
Multiple qualities were supported in the first version of Vime but it actually got a little tricky implementing it. I don't think there's any value to having this feature because it's much easier/better to support multiple devices, networks speeds and qualities via adaptive bitstreaming. I'll leave issue open for discussion, might still implement this back in but need to think about it.

Related: https://github.com/vime-js/vime/issues/76

**Comment by aolko** [comment]
Yet [every](https://github.com/silvermine/videojs-quality-selector) [other](https://github.com/sampotts/plyr#options) [player](https://support.jwplayer.com/articles/how-to-add-an-hd-quality-toggle) supports that ***for a reason***. You don't have to implement it based on speed or screen width or drop it entirely just because you want to. It's an essential video player feature.

**Comment by mihar-22** [comment]
Sounds good, use the other players that do support it :) I left it open for discussion and you can communicate with a little respect. Version 1 to where we are now was a complete rewrite that took a lot of work, I didn't simply drop it but I haven't decided whether to include it or not. I'm open to anyone creating a PR and including it which is exactly what happened for both Videojs and Plyr (quality selection were community contributions), these things don't come out of thin air and it needs to be worked on.

**Comment by silllli** [comment]
Despite the fact that I don’t like @aolko’s tone, I was somewhat surprised that the feature was removed. Of course it’s your decision and you have to decide what features you use your time on.

For whatever it’s worth: I would be happy if it came back! (But am currently in no position to make a PR myself.)

**Comment by lonelylion99** [comment]
Would love to see this feature.
