### ISSUE TITLE
Nextjs issue

### ISSUE THREAD

**Issue by nkrmr** [vime-js/vime#89]
Hi,

When I tried to deploy on Vercel with Next.js I had this issue : 
<img width="1008" alt="Screenshot 2020-10-05 at 15 38 56" src="https://user-images.githubusercontent.com/686395/95086528-e3600200-0720-11eb-94e5-e9e7a5d1f16e.png">

I used Vime like this
```javascript
import React, { FC } from 'react'
import { VimePlayer, VimeVimeo } from '@vime/react'

import {
  ModalChatContent,
  ModalChatContentVideo,
  ModalChatContentChat,
  // ModalChatContentVideoIframe,
  ModalChatWrapper,
} from './Style'
import { Chat } from '../Chat'

interface ModalChatProps {
  data: { name: string; video: string; description: string }
}

export const ModalChat: FC<ModalChatProps> = ({ data }: ModalChatProps) => {
  const { video } = data
  return (
    <ModalChatWrapper>
      <ModalChatContent>
        <ModalChatContentVideo>
          <VimePlayer controls>
            <VimeVimeo videoId={video} />
          </VimePlayer>
        </ModalChatContentVideo>
        <ModalChatContentChat>
          <Chat data={data} />
        </ModalChatContentChat>
      </ModalChatContent>
    </ModalChatWrapper>
  )
}
```

Someone knows this issue, I can't deploy my project

Best regards,

**Comment by mihar-22** [comment]
Hm I'm not really sure what's going on here @nkrmr, the error doesn't make sense because it's valid TypeScript. I'll need to investigate this a little more myself.

**Comment by nkrmr** [comment]
@mihar-22 Maybe it's a tsconfig issue, I try to investigate on it

**Comment by nkrmr** [comment]
It's works with the last version of typescript !
