### ISSUE TITLE
Menu for quality selection

### ISSUE THREAD

**Issue by RailgunWinjoy** [vime-js/vime#97]
How do I pick a quality myself from the Playback menu.
I have multi quality pre-encoded for the HLS but it shows only "auto"

`      <VimeHls
        v-else-if="playerOptions.sourceHls"
        version="latest"
      >
        <source
        v-for="source of playerOptions.sourceHls"
          :data-src="source.src"
          type="application/x-mpegURL"
          :label="source.quality"
        />
      </VimeHls>`

**Comment by mihar-22** [comment]
Hey @RailgunWinjoy I haven't added that feature just yet (open issue #76), it's on my priority list.
