### ISSUE TITLE
Mobile display wrong

### ISSUE THREAD

**Issue by RailgunWinjoy** [vime-js/vime#98]
The player hides itself on Mobile And It only works after i manually remove the class "mobile"

![image](https://user-images.githubusercontent.com/28724907/96597226-283e8800-1320-11eb-8c03-207335261cd8.png)
![image](https://user-images.githubusercontent.com/28724907/96597281-38eefe00-1320-11eb-80c2-d6751a055d70.png)

**Comment by mihar-22** [comment]
Hey @RailgunWinjoy that style is not part of Vime because it would be `vime-player.mobile` if it was. It's coming from somewhere else, maybe a library you're using?

**Comment by RailgunWinjoy** [comment]
Yeah Thank you and sorry for the delay. There's a third party widget and the css got confused
